### ISSUE TITLE
Consider disabling copy/paste

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#115]
Is there a simple way to disable copy/paste/select on checklist items? 

Some researchers have expressed the concern that compulsive parents may copy items and practice them (this comes up in the CUHK Hong Kong lab). Making things a little more difficult might help.

**Comment by HenryMehta** [comment]
Can't do this because user need to be able to click on screen

**Comment by HenryMehta** [comment]
This can be solved and I've put in code to do so.
