### ISSUE TITLE
Typo 'burb' (in pretending section of NAE W&G)

### ISSUE THREAD

**Issue by christinabergmann** [langcog/web-cdi#116]
Pretending to be a parent section (p28 of 29) has a misspelled word: Pat or burb it --> Pat or burp it
(At least our version)

**Comment by HenryMehta** [comment]
This can be changed via the Admin screens.  I have added a search field to the Instrument Forms Admin page (commit: e04545d8) which allows you to search for 'Burb', and you can then correct the spelling

**Comment by vmarchman** [comment]
fixed and closed
