### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#117]
@amsan7 could you try to document:

* [ ] how to set up locally
* [ ] how to (re-)deploy in case of problems
* [ ] dev/prod/deployment architecture description
* [ ] how to add a language
* [ ] admin FAQ: how to get back deleted data, how to reset someone's password, etc.

**Comment by vmarchman** [comment]
In case this helps, here is a google doc that Danielle made for me on how to set up a user.  https://docs.google.com/presentation/d/1oH167FXp4hfWBddvjwSs9FCisAzGIGjiHARUukFAi7Q/edit#slide=id.g3c8d7e4859_4_0

**Comment by dsathyan** [comment]
A docker-compose file will be ideal for anyone to try it out. I can add this if there is interest. And would need access to the above document :)

**Comment by HenryMehta** [comment]
Local setup & deployment (of changes) are now covered in `setup.txt`
