### ISSUE TITLE
demographics don't appear to download

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#118]
when you download a web-CDI administration, data from Basic Information form (demographics) is included in header, but does not populate.  CDI data do populate

**Comment by HenryMehta** [comment]
Hi Virginia, can you give more information about where this is happening.  Is it in `/interface/study/<study name>/` when you select `Download Data > Download Data (CDI scoring format)`?

**Comment by HenryMehta** [comment]
@vmarchman 
I think this is now sorted.  Please test and confirm.

**Comment by vmarchman** [comment]
Yes, this seems to be working but getting funny values in gender like "l" and "i"

**Comment by HenryMehta** [comment]
@vmarchman  I've made an amendment - I think this is now sorted.  Please confirm

**Comment by vmarchman** [comment]
Seems to be working.
