### ISSUE TITLE
Add Spanish Short Forms & Scoring/Benchmarking

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#128]

**Comment by HenryMehta** [comment]
@vmarchman Benchmarking/Scoring loaded (in 10 minutes)

**Comment by vmarchman** [comment]
Here are the corrected tables with response types in English but Scoring categories in Spanish.
[ScoringResponses_SpanishWG.docx](https://github.com/langcog/web-cdi/files/3503777/ScoringResponses_SpanishWG.docx)
[ScoringResponses_SpanishWS.docx](https://github.com/langcog/web-cdi/files/3503778/ScoringResponses_SpanishWS.docx)
[Spanish_WG_normingtables.xlsx](https://github.com/langcog/web-cdi/files/3503779/Spanish_WG_normingtables.xlsx)
[Spanish_WS_normingtables.xlsx](https://github.com/langcog/web-cdi/files/3503780/Spanish_WS_normingtables.xlsx)

**Comment by HenryMehta** [comment]
@vmarchman WG scoring specifies 396 items from sections 5 and 6 but the csv file has 428 items within sounds, animals, vehicles, food_drink, clothing, body_parts, toys, household, furntiure_rooms, outside, people, games_routines, action_words, states, time_words, descriptive words, pronouns, question_words, articles, quantifiers, locations, prepositions.

**Comment by HenryMehta** [comment]
@vmarchman These are now live and ready to test (with 428 items for sections 5 and 6)
