### ISSUE TITLE
submit button doesn't appear right away

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#131]
For English W&S and W&G, need to hit save button multiple times on last page for submit button to appear.  It flashes on the screen, but then disappears.  Finally, after several save attempts (3 for W&S and up to 6 for W&S), the green submit button finally appears

**Comment by vmarchman** [comment]
Just tested again and it took nearly 20 saves for the submit button to appear!

**Comment by HenryMehta** [comment]
@vmarchman 
Interesting.  I'm not getting this problem when I run the system locally.  I simply completed the form without pressing save once.  When I got to the final page the submit button was green and it accepted it immediately.  I've checked and all data is saved to the database.
I do get this issue within the dev environment.  I'm not sure what the difference is but I need to look into it.

**Comment by HenryMehta** [comment]
@vmarchman 
The issue, I believe is you were doing the test too quickly.  In order for the submit button to show you must get to the end, have clicked the captcha (if available) and taken at least 4 minutes.
