### ISSUE TITLE
Spanish translations of primary, secondary caregiver

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#136]
In Basic Information (Demographics) page for both Spanish WG and Spanish WS: 

Who is filling out this form: ¿Quien está llenado este questionnario?
Choices:  Madre, Padre, Abuelo/a, Otro

Primary Caregiver: Cuidador(a) principal
Primary Caregiver Year of Birth: Año de nacimiento del/de la cuidador(a) principal
Primary Caregiver Education: Nivel de educación del/de la cuidador(a) principal
Secondary Caregiver: Cuidador(a) secundario
Secondary Caregiver Year of Birth: Año de nacimiento del/de la cuidador(a) secundario
Secondary Caregiver Education: Nivel de educación del/de la cuidador(a) secundario,

**Comment by HenryMehta** [comment]
Ready to test
