### ISSUE TITLE
figure out what the "group studies" function does

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#141]
There is a function to "group study".  Not sure what this does.  Perhaps this functionality could be related to the goal of linking IDs across studies.

**Comment by HenryMehta** [comment]
I've been looking through the Group functionality.

I can work out how you create a Group and add Studies to it during creation.  
A Study can only be in one Group.
I cannot find a way to edit, view or delete a Group.

When a Study is in a Group, if you select the Study from the Research main page then it will show the Group below that and add a link within the Add Participants modal.  The link doesn't work and I'm not certain what the code is trying to do.  

I cannot see the Group functionality being used anywhere else.

I think we need a clear specification of the purpose Group functionality and how it should work.

**Comment by HenryMehta** [comment]
Aim is to link participants across studies.  Currently subject_ids are for a specific participant within a study but this subject_id must be across studies in a grouped study with the readministration number increasing.  OR administration number within Study and group administration number within grouped study
