### ISSUE TITLE
provide summary score template for English WS

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#143]

**Comment by HenryMehta** [comment]
I've now made modifications to provide the scoring functionality. I believe you want this on the CSV download so I've added columns to the end of the CSV. The titles of the columns are the titles of the item_type (which aren't great but should be able to beautify if this works) within the csv file which uploads the surveys, which I believe corresponds exactly to your scoring requirements. The values are then meant to be as you've specified. The database doesn't necessarily hold them as "Yes". For examples it stores "produces" when Part 1. If I've missed one of the positive keys then the numbers will not add up.

I believe is should work for the WS and short forms. I think I'm missing keys for the WG surveys.

If this seems to be working, it needs a really thorough test.

**Comment by HenryMehta** [comment]
I've decided it would be easier to keep scoring under 1 issue so I'm closing this and including it in issue 97: https://github.com/langcog/web-cdi/issues/97
