### ISSUE TITLE
All words are capitalized should be lower case

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#159]
All words from the word lists are now capitalized in stead of just lower case. The Dutch version does not have capitals. Is it possible to remove this?

**Comment by HenryMehta** [comment]
Discussed with @vmarchman  and we're going to make lower case once Virginia has confirmed with Krista re French

**Comment by HenryMehta** [comment]
Ready to test

**Comment by Cielke-Hendriks** [comment]
The capitalization seems to go right except for items with parentheses at the beginning of the word (e.g. (hals)ketting)). For these words the first letter after the opening parenthesis is capitalized, e.g., (Hals)ketting.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks Do you mean it should be capitalised in this case (ie when an item begins with parentheses).  If so, you now need to provide it within the csv with a capital letter.

I've checked locally and the csv has it in lower case and it shows on the form in lower case so I consider this working

**Comment by Cielke-Hendriks** [comment]
It should not be capitalized, but yes it seems to be working properly now!
