### ISSUE TITLE
Study participant limit not working

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#161]
I tried to limit a study to 50 participants in the "update study" dropdown menu, but 73 administrations of the study (titled norming_pilot_wg_6_19) were collected.

**Comment by HenryMehta** [comment]
@benjamindemayo 
I need a little more information.
1. Have you seen this working?
2. How did you generate the links?
3. What are the other ways you can generate the links?

**Comment by benjamindemayo** [comment]
1. I haven't used it long enough to see this feature working.
2. I generated the links by clicking 'Add Participants' and copying the Single Reusable Link
3. I don't know of other ways to generate a single reusable link.

**Comment by HenryMehta** [comment]
@benjamindemayo 
Thank you.  So based on the code I do not believe there is anything in place to actually limit the number of participants.
