### ISSUE TITLE
French Questionnaires have some English text

### ISSUE THREAD

**Issue by hilary-rose** [langcog/web-cdi#166]
There is a bit of English appearing on the French form. In both versions of the French form (Mots et Gestes as well as Mots et Enoncés), the first bullet point in the first section "Directives pour remplir l'inventaire de communication" reads: "Try to complete the inventory when you have at least 10-15 quiet minutes, without interruptions. An example might be when your child is sleeping." Instead, it should read: "**Essayez de compléter l’inventaire lorsque vous avez au moins 30 minutes sans interruptions. Un exemple pourrait être lorsque votre enfant dort.​**" The other bullet points and the header are correctly written in French.

**Comment by HenryMehta** [comment]
@vmarchman, @hilary-rose 
I need to look at this a bit more.  I applied the translation but it didn't take.  I've also noticed, it is not translating into Spanish either so there is some strange character (or an extra space or something) that isn't being picked up properly in the English so the translations aren't working.

**Comment by HenryMehta** [comment]
@hilary-rose @vmarchman , Sorted - this is ready to test.  Virginia, the error was when we added the different text for the short forms it stopped showing the original text.  This has been fixed.  If you could confirm tested, I'll set it ready to go-live.
