### ISSUE TITLE
Not able to download data in CSV or summary format

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#168]
When I try to download data in CSV or summary format from the `Download Data` dropdown menu, I get a 504 Gateway Time-out error. I'm able to download some participants at a time, but if I select all participants individually and try and download all of their data, I run into the same issues.

**Comment by vmarchman** [comment]
@benjamindemayo @HenryMehta I get an error for particular studies (in my case, fb3, fb4) but not other studies.  This is not a timeout error, but looks like this: 
![image](https://user-images.githubusercontent.com/7682636/62659368-06760280-b920-11e9-9ae8-93fcf8a242ec.png)

**Comment by vmarchman** [comment]
Perhaps this only happens with a large number of participants (e.g., > 50?).

**Comment by HenryMehta** [comment]
@benjamindemayo This is a timeout issue due to volume of data and happens when you're trying to download more than about 250 responses in a single go.  It is down to the amount of processing that needs to take place to calculate the scoring and benchmarking

@vmarchman your error is that none of the participants (according to this) that you've selected have completed the study.  We need 1 completed study in order to build the benchmark and scoring titles.

**Comment by itang1** [comment]
I'm getting a 500 server error when trying to download data (csv format), even when downloading only one participant at a time. No problems with the other three formats.

**Comment by HenryMehta** [comment]
@itang1 could you give me the study and any specific item not working please. Or is it absolutely all?

**Comment by itang1** [comment]
All

**Comment by HenryMehta** [comment]
And all studies?

**Comment by itang1** [comment]
All studies, all participants, have tried Chrome and Safari, all just return a blank page saying nothing but "Server Error (500)"

**Comment by HenryMehta** [comment]
@itang1 I have made a code change and loaded it to live - please confirm now working.

**Comment by itang1** [comment]
I just downloaded successfully , thank you so much!

**Comment by HenryMehta** [comment]
@vmarchman 
I've done some work on the processing speed for downloading datafiles.  Locally I saw improvements between 25% and 75% depending on size of group and actual number of responses

**Comment by vmarchman** [comment]
Great!  thanks!
