### ISSUE TITLE
waiver language

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#170]
Here's the updated Waiver language.  In English:  (Title on p. 1): Waiver of Documentation of Informed Consent.
(Title if they say no): Waiver Denied.
(Inside the box:) Thank you for your response. We are unable to continue. Please close the window.  If you would like, you may review the Waiver.

In French: Demande de Dispense de la Documentation du Consentement Éclairé.
Demande Refusée.
Merci pour votre réponse. Il n’est pas possible de continuer. Veuillez fermer la fenêtre. Si vous le souhaitez, vous pouvez revoir la Dispense.

In Spanish: Renuncia a la Documentación de su Consentimiento.
Renuncia Denegada
Gracias por su respuesta. Por el momento, no podemos continuar. Por favor cierre la ventana. Si desea, puede repasar el documento de exención.

**Comment by HenryMehta** [comment]
@vmarchman 
I'm also going to need translations for the "Review Waiver" button on the Waiver Denied modal

**Comment by vmarchman** [comment]
revised language for Spanish:

In Spanish: Renuncia a la Documentación de su Consentimiento.
Renuncia Denegada
Gracias por su respuesta. Por el momento, no podemos continuar. Por favor cierre la ventana. Si desea, puede revisar la renuncia a la documentación de su consentimiento.

Review Waiver: Revisar el documento de renuncia

**Comment by vmarchman** [comment]
For Spanish: last sentence should be:  Si desea, puede revisar la renuncia a la documentación de su consentimiento.

**Comment by HenryMehta** [comment]
@vmarchman Sorry - missed that.  Amended and loading now - will be there in 10 minutes
