### ISSUE TITLE
Instructies Dutch WS needs to be changed

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#175]
The instruction part including the pictures does not fit with the answering options for the Dutch WS (which is both understands and understands and says). Could the instruction part of the Dutch WS be made similar/identical to the instructions of WG, since the answering categories are the same as the WG form.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
Surely this can be produced by making your translation and images for WS the same as WG?

**Comment by Cielke-Hendriks** [comment]
Yes that would do the trick
