### ISSUE TITLE
Instructions at vocabulary checklist only once

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#176]
Currently there are instructions at the top of every page of the vocabulary checklist. Would it be possible to have those instructions only once, at the top of the first vocabulary checklist? I.e., only at the category sounds, instead of all the categories.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
This is possible but will require substantial code changes.  Can you live with it with instructions on each page?

**Comment by Cielke-Hendriks** [comment]
I guess I can live with that.
