### ISSUE TITLE
Cannot administer new subjects

### ISSUE THREAD

**Issue by itang1** [langcog/web-cdi#180]
Good morning WebCDI administrators,

Our researchers are trying to administer a new participant; that is, we are trying to generate a WEBCDI link for a new participant with a particular Subject# under a particular study. The website is currently not allowing us to do this. We have tried using different subject numbers and different studies.

We first noticed this at ~6:50amEST (now ~9:30amEST at the time of writing).

Steps to reproduce:
We click the Add Participants button > In the New Subject IDs field, we type '21' for the subject number > when we click the Submit button, nothing happens

**Comment by HenryMehta** [comment]
@itang1 0- Emergency fix just gone up - this should be working now.  Please confirm so I can close this issue.  thanks

**Comment by itang1** [comment]
Working, thanks so much!
