### ISSUE TITLE
waiver page take images (non text)?

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#181]
We would like the Waiver of documentation splash page to be able to show a picture/image/screenshot.  Can this box take more than text?  Can we also add formatting options to the text functionality?

**Comment by HenryMehta** [comment]
@vmarchman 
This is now ready to test.
On Firefox you cannot edit the image size, but I've tested on Chrome, Edge, IE and Safari as well and they all work - as it is generally only developers that use Firefox, I'm going to assume it is ok.

An explanation on how to load images is given in this video: https://www.youtube.com/watch?v=ZKvx6RHNpCE&feature=youtu.be

**Comment by vmarchman** [comment]
@HenryMehta This works great!  Thanks.  Can we remove the text on the top of the box altogether? ("Documentation of waiver of informed consent")
