### ISSUE TITLE
Different instruction above word category for list 1 and 2 until end

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#182]
We would like an abbreviated version of the current instruction above word list category 2 until the end compared to the first word list category.

**Comment by Cielke-Hendriks** [comment]
Another possibility would be to make the instruction text collapsible (from word list category 2 onward) so parents can unfold it if they want to read it again.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks @vmarchman 
On multiple page sections the section instructions are now collapsible (including on the first page of the instructions).  They start open on the first time entering the main section then once collapsed will remain collapsed as the parent works through the study
