### ISSUE TITLE
Trouble with single reusable link

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#188]
More participants are added than are anticipated/expected.  Perhaps because of manipulating link in the system setting up Facebook ads?  @benjamindemayo any insights?

**Comment by HenryMehta** [comment]
The issue is that when someone clicks the link it automatically creates a record whether the parent completes any data or not.  One solution might be to not create a record until they submit complete background information

**Comment by vmarchman** [comment]
@HenryMehta I discussed with Benny and we both think that this is a good solution.  Please proceed.
