### ISSUE TITLE
Initial Dataload

### ISSUE THREAD

**Issue by HenryMehta** [langcog/web-cdi#190]
When trying to set up a new local version I am experiencing problems with the dataload (`manage.py import_datasets`).  This is just an example, but when trying to load Slovak_WS (Kapalokova) it is erroring.  This has a new_words type for item_648.  The possible responses in the dataset are 0,1,2 (I think) but the only response within the database is "produces".  How should are map these numbers to the database structure? 

I was expecting the files within raw_data to all load without issue because I expect them to have already been run.

Similarly, but different, I'm also experiencing a problem trying to load Kigiriama WS.  The error is no age against a data row so it crashes.  I've looked at the Kigiriama data I downloaded and counted the records in the dataset compare to the number Wordbank says it has loaded.  The are 205 loaded but there are 232 in the dataset.

I have not progressed past this dataset so I don't know if there are other issues;  I would like to try and get some agreement or clarity before progressing.

**Comment by mcfrank** [comment]
I believe these datasets were imported by @daniellekellier - Danielle, any chance you can explain what you did?

**Comment by daniellekellier** [comment]
Hello! Normally the values are mapped to the files in the raw_data/instrument/*_values.csv file
For instance, item_648 is a "new_words" type but there is no row in "SlovakWS_Kapalkova_values.csv" that specifies that type of field and the possible value mappings.  I do not remember that specific field type when I originally imported the Slovak data. That may have been a new addition or edit to a previous file type. I recommend going into older versions of the raw_data/Slovak_WS/ folder to see when that value was added. In regards to mapping, that is up to you. If the only possible response to the data is "produces", then I would guess that 2 = produces and 0 = none.
For the Kigiriama data, I am not quite sure what you mean exactly. 
Sorry! Everything is a little fuzzy so I can't remember everything.

**Comment by HenryMehta** [comment]
I've just realised I raised this in webcdi rather than Wordbank - sorry.
Thanks @daniellekellier, by tracking back the commits I can see that the item was originally set as "combine" and was changed to "new_words" later without the the `_values.csv` file being updates.  I can only assume it wasn't rerun
