### ISSUE TITLE
summary outputs

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#211]
We are testing data collected before the holiday and Summary Level outputs are not working for both WG and WS.  Item level outputs are fine, but Summary Level outputs give 0 for all variables (when the scores are not 0).

**Comment by HenryMehta** [comment]
I have a fix for this but would like to hold off and put it live when Hebrew goes live.  Would that be an issue?

**Comment by vmarchman** [comment]
@HenryMehta Not ideal since I worry that people may not realize that their output is all 0s and import to another data sheet, etc.

**Comment by HenryMehta** [comment]
@vmarchman 
ok - I'm working on splitting it from the Hebrew code and will put into development for you to test

**Comment by HenryMehta** [comment]
@vmarchman 
That has taken some time to split the code.  I've now loaded the corrected summary to webcdi-dev.  Could you test and ensure you're happy and I'll put it live.

**Comment by HenryMehta** [comment]
Put Live on 9th Jan 2020
