### ISSUE TITLE
time to complete

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#215]
The allowable time to complete is currently set at 4 mins, but we have participants with the difference between record creation and last modified as low as 3.0 mins

**Comment by HenryMehta** [comment]
@vmarchman 
I believe this is a rounding error and setting 4 minutes allows 3min1sec if the parent started 1 second before start of new minute on the PC clock.

I have reverted webcdi-dev to the 6 minutes previously used.  Please test and confirm

**Comment by HenryMehta** [comment]
#218 Put Live
