### ISSUE TITLE
no way to turn waiver box off

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#216]
When waiver box was just a text box, if there was nothing in the box, the waiver box would not show up for the user.  Now, we have made the box fancier (to allow images, etc), and now the waiver box shows up even if the user has not put anything in the box

**Comment by HenryMehta** [comment]
All you have to do is delete everything within the waiver box.  If you go into the waiver box, do CTRL-a (CMD-a on Apple) and delete and save that, it shouldn't open the waiver box.

I've tested in development and it works for me

**Comment by vmarchman** [comment]
ok - this works now for me with just text in the box.  @Benjamin Edward
deMayo <bdemayo@stanford.edu> can you test with one in which you had put an
image?
