### ISSUE TITLE
Functionality for "opt out" of broader sharing

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#222]
some participants would like their data to be excluded from broader sharing (e.g., shouldn't be downloaded in large-scale data downloads by default). 

is there a good way to have this flag present in the researcher interface but not set by default, so that then researchers can "opt out" their participants by just activating that flag? @vmarchman

**Comment by HenryMehta** [comment]
@vmarchman 
Available to test - please note, this works on an administration by administration basis for the respondent.  If there have been 2 administrations they must be opted out on both records.
