### ISSUE TITLE
bug in output

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#223]
Output is wrong for Admin ID #102298 (1,364 Word Produced) for WS.  Study Name is UBC Infant Studies Center - Priming_Rep

**Comment by HenryMehta** [comment]
I don't know what it was wrong but I ran the update summary function against administration 102298 and the numbers look okay now.  I do not know how they could have been corrupted unless someone was editing the table manually at the same time.  Anyway - if you check it in production now, it should be ok
