### ISSUE TITLE
Links to Canadian English "Words and Sentences" form gives 505 server error

### ISSUE THREAD

**Issue by hilary-rose** [langcog/web-cdi#232]
One of our participants got in touch with us to say that when she pressed "submit" after filling out the Canadian English Words and Sentences form, she got an error message. So she tried to re-click on the link we sent her, but it led to an error page. I just logged in as a researcher and tried clicking on the link to any Canadian English Words and Sentences form, and I also get a 505 error page. For the Canadian French Mots et Enoncés form, when I click on the link, the completed questionnaire shows up as normal.

Can you please look into this?

Warmly,

Hilary

**Comment by HenryMehta** [comment]
Working on it

**Comment by HenryMehta** [comment]
Short answer it you will be getting the error on Canadian WG as well.  I have a fix which I'm implementing now direct to Production

**Comment by HenryMehta** [comment]
@hilary-rose Fix should be loaded in 20 minutes
