### ISSUE TITLE
preselect country in background question

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#235]
For the country question in the background questions, preselect the appropriate country for a specific cdi. So for the Dutch cdi, have Nederlands as pre specified country.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
I'm currently working on this.  The current zip code is validated to meet US standards.  What to Dutch postcodes look like?

**Comment by HenryMehta** [comment]
@Cielke-Hendriks available to test in 20 mins
