### ISSUE TITLE
Postal code for Dutch forms

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#248]
For the background questions: we would like to, when Netherlands is selected in the country question, also display the postal code question.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks
I'm currently working on this. The current zip code is validated to meet US standards. What to Dutch postcodes look like?

**Comment by HenryMehta** [comment]
@Cielke-Hendriks available to test in 20 mins
