### ISSUE TITLE
Change age boundaries

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#251]
The current age settings allow the following:
WG: 7 months 15 days – 18 months 14 days
WS: 15 months 15 days – 30 months 14 days
 
While the age ranges should be:
WG: 8 months 0 days – 18 months 30 days
WS: 16 months 0 days  – 30 months 30 days

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
I need more information about where you're seeing this.  I've gone where I think the calculation takes place and it looks right to me.  Here is a video explainer: https://youtu.be/7V2zpbiZQX8
