### ISSUE TITLE
No way to reach ending demographics if age needs to be confirmed in WG2/WS2

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#257]
In WG2/WS2, in "Update Study", I just noticed a bug if the following box is checked:
> "At the end of the form, would you like parents to confirm the age of their child and that they completed the entire test? (Best for anonymous data collections where you haven't personally vetted each participant)"

If this box is checked, once the participant finishes the regular survey items, they end up at the page that asks them to confirm that they completed the entire survey and asked to click the Captcha box. However, there is no way to continue from this confirmation page to the ending demographics page, which is where the participant would submit the survey.

**Comment by HenryMehta** [comment]
@benjamindemayo 
I don't understand.  I completed the form, went to the age confirmation page and confirmed.  Having done that I got to the demographics page (i didn't have a Captcha because I don't have vouchers going out)
