### ISSUE TITLE
Add redirect link as study option

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#260]
@HenryMehta I'm so sorry to add another issue while you're recovering from diverticulitis.

We'd like to be able to add a study option that would allow researchers to include a link at the end of the survey to which the participant would be redirected. 

So, when creating the study (i.e., after clicking `New Study`), the participant would see a toggle checkbox asking something like, "Would you like to include a link at the end of the survey to redirect participants?" If selected, this option would allow researchers to input a URL, that would then be displayed to the participant at the end of the survey (_after_ the participant clicks "Submit") for the participant to be redirected to some other page.

@vmarchman

**Comment by HenryMehta** [comment]
@benjamindemayo @vmarchman 
Is this an automatic redirection so that they do not get to see their graphs etc or is this an link that will show on the graphs page that they can select if they want?

**Comment by benjamindemayo** [comment]
@HenryMehta thanks for this question, apologies for the slow reply. @vmarchman and I were discussing. I think we want a redirect upon a button click. I think the best way to do this would be to have some text on the graphs page that says "Click finish to complete the study", along with a button that says "Complete study" that the participant would then click to redirect them to the URL specified by the researcher. 

I have no sense of how difficult this would be to implement. I think if it's very complicated, an automatic redirect without showing people graphs etc. is probably fine; Virginia can weigh in with thoughts as well.

**Comment by benjamindemayo** [comment]
@HenryMehta adding on to this, the other change we need to make for prolific is that we need to be able to capture the participant's Prolific ID. This can either be done by querying the participant to enter a text string of the prolific ID, or the Prolific ID can be passed through as a parameter that we capture when the participant clicks the study link in Prolific. Researchers would be able to enable this functionality upon checking a box in the 'Create study' box that asks 'Would you like to run this study on prolific and collect participants' Prolific ID's?'

The instructions regarding how long the participant has to complete the survey should NOT be altered for prolific.

**Comment by HenryMehta** [comment]
@benjamindemayo 
This is available to test.  Please test and confirm working.

I have moved Prolific to a new issue
