### ISSUE TITLE
[Researcher Interface] "Show all" (participants) doesn't allow sorting

### ISSUE THREAD

**Issue by christinabergmann** [langcog/web-cdi#266]
The researcher interface has a bug when there are more than 20 participants (the maximum number shown at a time). When clicking show all to reveal the remaining participants, and then wanting to sort, e.g. by whether the study was completed, it reverts to the default display of 20/page. This makes selective readministration a bit tricky / requires the generation of unnecessary readministrations.

**Comment by HenryMehta** [comment]
@christinabergmann 
I've made a change in development.   Could you test and confirm it is working as expected please.
Thank you
