### ISSUE TITLE
incorrect conversion from lbs to grams in background info

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#267]
In the dropdown menu of the question asking for the child's birthweight, some of the conversions from lbs/oz to grams are incorrect. I've attached a photo of what I believe are the correct conversions. 
<img width="477" alt="Screenshot 2020-05-08 10 47 33" src="https://user-images.githubusercontent.com/20076061/81433617-b4b21100-9119-11ea-9b34-79a6f9c44c6b.png">

**Comment by HenryMehta** [comment]
@benjamindemayo 
Amended in development.  Please test and confirm it is right

**Comment by benjamindemayo** [comment]
Looks good, thank you!
