### ISSUE TITLE
Spanish gift card message

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#269]
The 'sorry we're out of gift card' message at the end of Spanish has some minor verb conjugation inconsistencies.

Right now it's this: 
> ¡Gracias por su interés en completar el Inventario de Desarrollo Comunicativo de MacArthur-Bates (Inventario)! En este momento, todos nuestros espacios de estudio ya se han llenado y nos hemos quedado sin regalos de agradecimiento para compensarle por su tiempo. Si todavía está interesado en completar el Inventario y aprender más sobre el vocabulario de su niño(a), puede hacer clic aquí para completar el cuestionario de 30 minutos. Si tiene alguna inquietud sobre el desarrollo de su niño(a), le recomendamos que hable con el médico de su niño(a). Si disfrutaste de nuestra evaluación, puedes obtener más información sobre el Inventario aquí. Nuevamente, apreciamos su interés!

Second to last sentence should be:
> Si disfrutó de nuestra evaluación, puede obtener más información sobre el Inventario aquí.

**Comment by HenryMehta** [comment]
@benjamindemayo Amended - please test

**Comment by benjamindemayo** [comment]
Will do in the morning, thanks
