### ISSUE TITLE
Zip code

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#273]
The zip code is partly obfuscated in the downloaded data. It only shows the first 3 digits, while for Dutch we need the first 4 digits to extract the region.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks , @vmarchman 
I'm loading this to dev now.  

When we have a zip code, the US it treated as an exception and and safe harbor guidelines are applied (ie last 2 digits become **).  For all other countries the post code is as provided.

However, the zip code is only requested when either the Netherlands or US is selected as the country.

Therefore we get abbreviated post code for the US, full post code for Netherlands and no post code for anyone else.

Apologies for switching between post code and zip code - please read them as interchangable
