### ISSUE TITLE
Error message when parents type to much characters in comment box

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#285]
When parents type to many characters in the comment box, can an appropriate error message be generated so parents know what the problem is? Perhaps the evaluation of the amount of characters can take place when they click on next page.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
What's happening at the moment?  I did a quick test and it seems to progress to the next page without saying the text.  Is that right?

**Comment by HenryMehta** [comment]
@Cielke-Hendriks Just made an improvement to also give a counter of number of characters remaining

**Comment by Cielke-Hendriks** [comment]
I think this is perfect, thank you. Maybe you could add "tekens over" (characters remaining) after the counter, to make it more clear to the parents what the number is about.
