### ISSUE TITLE
Text in comment box is cleared when clicking on Save

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#286]
When clicking on save in between pages, the text in the comment box on the current page is cleared.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
It isn't getting cleared for me.  Could you check in dev please

**Comment by Cielke-Hendriks** [comment]
I've just checked both WG and WS in dev and the text on the current page is still getting cleared when I click on save.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
What browser are you using?  Do you get the same results in Firefox?

**Comment by Cielke-Hendriks** [comment]
I've used Chrome. I just tried Firefox and I get the same results

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
I cannot replicate the issue so I think I'm doing something wrong.  Please see here: https://www.youtube.com/watch?v=7nO0jKHZw1A

**Comment by Cielke-Hendriks** [comment]
Ah yes, you clicked on next page first and then on save. But if you don't click on next page and directly on save, it will not save the message.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks deploying an update to development now - should be ready to test in 20 minutes

**Comment by Cielke-Hendriks** [comment]
It works now. Thank you.
