### ISSUE TITLE
toggle demographic information completely off

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#289]
For bilingual administration, give researchers option to toggle demographic information off

**Comment by HenryMehta** [comment]
Can't you do this when using the split background information forms alongside the "Show backpage in split background information study? " toggle in the study modal?

**Comment by vmarchman** [comment]
got it.  thanks @HenryMehta

**Comment by vmarchman** [comment]
Yes, we would want it system-wide.
