### ISSUE TITLE
CAT CDI Splashpage - Flipped easiest and hardest words

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#291]
It seems like the easiest and hardest words reported at the end of the `Computer Adaptive Test` CDI are flipped (eg 'Thank you for filling this out! Of the words we asked, the hardest word your child knows is "ball" and the easiest word is "make". ')

**Comment by HenryMehta** [comment]
@JMankewitz 
Deploying to dev now.  The API is giving me these back as hardest and easiest so I've just switched them rather than amending the API.  If this is then giving the right results I'll look at the API but it is in R, which is not my strength so will take me a little longer

**Comment by JMankewitz** [comment]
Tested, looks good.
