### ISSUE TITLE
CAT CDI Splashpage

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#292]
The final splashpage for the `Computer Adaptive Test` CDI is much shorter than the `Words and Sentences` CDI. I think we'd like them to be comparable. Maybe something like:

> Thank you for taking the time to complete the MacArthur-Bates Communicative Development Inventory (CDI). With the help of parents and caregivers like you, we are working to learn more about the way that children’s language develops, and how that development varies across individual children and cultures. Remember that the CDI lists many different words that are used by many different children. Don’t worry if your child only knows a few of them right now. If you have any concerns about your child’s development, we recommend that you talk with your child’s physician. If you enjoyed our assessment, you can learn more about the CDI here. We appreciate your contribution!

**Comment by HenryMehta** [comment]
@JMankewitz Deploying to dev now.  I've added below the easiest/hardest bit because I didn't know if you wanted both

**Comment by JMankewitz** [comment]
This works, looks great.
