### ISSUE TITLE
CAT CDI - Download Selected Data Error

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#293]
In the Computer Adaptive CDI on dev, I get this error while trying to `download selected data`->`Download Selected Data (CSV/All)`:
```AssertionError at /interface/study/CAT_CDI_Comparison_Short ```
```Could not find any CDI items registered with this instrument: English_CAT```

And this error when I try `Downlad Selected Data` -> `Download Summary (CSV format)` (even though the participant has data in the full data report for the full study):
```There are no data in the study(ies) to report```

**Comment by HenryMehta** [comment]
@JMankewitz 
Deploying fix now

**Comment by JMankewitz** [comment]
Tested, can now download specific participant's data. Good to go.
