### ISSUE TITLE
Custom splashpage option

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#294]
Hello!

It would be really wonderful if researchers could add a custom message at the end splashpage for their individual study, in addition to or instead of the reported statistics/graphs. Is this something we can do?

**Comment by HenryMehta** [comment]
@JMankewitz @vmarchman 

Yes, we can do this but could I have a little more information about what you would want.

Is it select one of Standard message, Bespoke Message or Combined Message (will show standard followed by combined) with the default being Standard Message with an area for the research to type a richtext bespoke message

**Comment by JMankewitz** [comment]
That sounds right!

**Comment by HenryMehta** [comment]
@JMankewitz 
Deploying to dev environment now.  I've added a couple of fields to the Create / Update study modals which allows you to select which end screen combination you want (standard, bespoke or combined) and to add the bespoke text

**Comment by JMankewitz** [comment]
Tested, looks good.

**Comment by JMankewitz** [comment]
Actually, sorry about this @HenryMehta but it seems like the link on the "Standard" splashpage (specifically at the line "If you enjoyed our assessment, you can learn more about the CDI here.") is missing. Is it possible to get that back?

**Comment by HenryMehta** [comment]
@JMankewitz 
Deploying amendment to dev now.  Please confirm fixed when you've tested - thank you

**Comment by JMankewitz** [comment]
Hi! One comment - it it possible to switch the order of the messages in the combined option, so it is the custom message above the standard message?

It may also be more clear to change the label of this message from "bespoke" to "custom". This is just a suggestion to make the "end message" box clearly linked as the "bespoke/custom" option.

**Comment by HenryMehta** [comment]
@JMankewitz 
Order amended and I think I've done as requested re bespoke.  Please confirm

**Comment by JMankewitz** [comment]
This looks great, thanks!
