### ISSUE TITLE
Broken CDI Links on Dev/No expiration message

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#295]
I pregenerated 100 CDI links for the WebCDI administration on 9/24/2020, but on 10/9/2020 I got this error (attached below).

For replication:
Researcher account: langcoglab
Study: CAT_CDI_Comparison_Short

Issue: Participants 1-100 have links that break to the RelatedObjects error. Example broken link (participant 100) https://webcdi-dev.stanford.edu/form/cat/fill/fc692f39a9b0e85a7e2cc53cc97921367f0c63f91e0a0772d9be4c3ddf7cdd78/

Suspicion: The links were set to expire after 14 days (the default), but instead of getting a "Unfortunately the time allowed to complete..." message, it returned an error because the administration had closed. 

<img width="1310" alt="Screen Shot 2020-10-09 at 10 07 49 AM" src="https://user-images.githubusercontent.com/8647029/96164277-d9cc5c00-0ecf-11eb-86db-66e9df2985ed.png">

**Comment by HenryMehta** [comment]
@JMankewitz 
Fix deployed

**Comment by JMankewitz** [comment]
Tested and closed, thanks!
