### ISSUE TITLE
HTTPS and mailserver setup

### ISSUE THREAD

**Issue by AshwinParanjape** [langcog/web-cdi#3]
Need HTTPS credentials and a mailserver

**Comment by mcfrank** [comment]
need to do this on EC2, look into it and email ashwin

**Comment by mcfrank** [comment]
We'll be using Amazon SES (simple email service) with the python Boto package:

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/Welcome.html
https://boto3.readthedocs.org/en/latest/reference/services/ses.html

we're waiting on Stanford to verify the web-cdi.stanford.edu domain and then we can use this library to send email. 

https://boto3.readthedocs.org/en/latest/reference/services/ses.html#SES.Client.send_email

**Comment by mcfrank** [comment]
won't include for now.
