### ISSUE TITLE
password reset link not working?

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#302]
When I try to reset my password, I never receive an email.  Checked spam folder too.

**Comment by HenryMehta** [comment]
Has someone changed the gmail password that deals with the emails?  This was the issue last time

**Comment by JMankewitz** [comment]
Hi @HenryMehta! What is the email address that is hard coded to deal with the passwords? We're trying to trackdown who has access to the password after Benny left.

**Comment by HenryMehta** [comment]
webcdi.contact@gmail.com

**Comment by JMankewitz** [comment]
It seems that the password sent to me does work, but it needed 2fa to log in. I'm not sure how this could/is effecting the reset password option but it might be related.

**Comment by HenryMehta** [comment]
@vmarchman @JMankewitz Found the error and deploying now

**Comment by vmarchman** [comment]
Thanks @HenryMehta!  Seems to be working now!
