### ISSUE TITLE
fix typos in Spanish WG (level I) and WS (Level II) short forms

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#306]
I have the changes to be made, but will need the files to edit, including instructions, demographic, and items.

**Comment by HenryMehta** [comment]
@vmarchman 
I don't have any Spanish short forms on the system.  I attach the English meta files.  I will also need the csv (but I assume the list is different or would you like me to include those as well).

[Shortforms.zip](https://github.com/langcog/web-cdi/files/5535606/Shortforms.zip)

**Comment by vmarchman** [comment]
Ok @Henry <hjsmehta@gmail.com> I will work on making the Spanish short
forms.

**Comment by HenryMehta** [comment]
@vmarchman 
Deployed and ready to test but a few issues.
1.  the CSV file came through with invalid characters.  I'm guessing you've edited the file in Excel and then saved to csv.  Characters have become invalid in the process of converting to utf-8.  I've had this problem with other languages and never remember how I fix it but if you send the the xls file I should be able to sort.
2.  We need a meta.json file for the sections to be defined.  I took a copy of the English but you'll need to translate text and title sections in the file.
3.  We need a scoring.json file.  Again I took the English and again you'll need to translate the title
4. Graphs.  I've just used titles col_1, col_2 and col_3.  If you want something else, please let me know

[Spanish_L1_meta.zip](https://github.com/langcog/web-cdi/files/5565125/Spanish_L1_meta.zip)

**Comment by vmarchman** [comment]
Hi @HenryMehta I've uploaded two files for the Spanish Level 1 short form.  One is the updated item list, hopefully converted to UTF-8 without messing up the accents.  Two, is the meta.json file with the instructions.  Hopefully, this will get them up and running.  We can deal with scoring later? :-/

**Comment by vmarchman** [comment]
uploaded to slack

**Comment by HenryMehta** [comment]
@vmarchman 
Those seems to have worked perfectly.  Deploying to dev now for you to check.  I also attached the English L2A and L2B meta.json files for you to translate to Spanish versions.
[English_L2.zip](https://github.com/langcog/web-cdi/files/5572034/English_L2.zip)

**Comment by vmarchman** [comment]
@HenryMehta Great!  Level 1 Short form test looks good.  Will slack you the files for Level 2A.  There is only one version of Level 2 for Spanish.

**Comment by HenryMehta** [comment]
@vmarchman 
Spanish L2A is loaded and ready to test
