### ISSUE TITLE
change what is plotted in graph at end of WS and WG

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#308]
@HenryMehta Right now, the graphs plot the proportion of items within each category that the child is reported to understand/produce, e.g., it there are 20 words in the Animals category list and the child is reported to say 2 of them, the plot shows 10% for that category.

Philip Dale feels it is more intuitive to have the denominator be number of positive responses that is reported by the parent (not number possible in the category).  So, if the child is reported to say 100 words total, and 10 of those words come from the Animal category, the plot should show 10% in the animals.  This tells the parent, of the words that your child knows, 10% of them are words for Animals.

I don't think this change will be a big deal for users, but seems a bit more intuitive for parents.

**Comment by HenryMehta** [comment]
@vmarchman As a parent, I don't agree with Philip because if you know 3 words in a category of 4 that's 75% but 10 words in a category of 20 is only 50%.  But I'm not an expert.  I've amended so that it plots both as a percentage in category and as a percentage for the child.  It is ready to test
