### ISSUE TITLE
Server Error (500) after submitting CAT CDI demographic information 

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#316]
Hello! 

Participants are hitting a server error 500 after the demographic information for the CAT administration.

The English WS seems fine.

Test link: http://webcdi.stanford.edu/interface/langcoglab/CAT_CDI_COMP_WS_v2/new_parent/?prolific_pid=test

**Comment by HenryMehta** [comment]
I’m just out at the moment. Home in an hour. Will look then

**Comment by JMankewitz** [comment]
No huge rush! I've paused data collection and only had to tie up loose ends for a few participants. Thanks for getting to it!

**Comment by HenryMehta** [comment]
@JMankewitz 
Is this a study using the split demographics?

**Comment by JMankewitz** [comment]
This study is a split backpage study with confirmation questions. 
Study title is "CAT_CDI_COMP_CAT_v2"
It was set up yesterday + tested yesterday. We successfully received submissions from 5 participants before 9am PST, so I assume the error is due to a change that went live around then? 

A note: We are using the prolific parameter, but I don't think this is related to the error.

**Comment by HenryMehta** [comment]
@JMankewitz Please test 1 again now and see if it works.

Problem with go-live process if it does.

**Comment by JMankewitz** [comment]
Looks like it works now!

**Comment by JMankewitz** [comment]
Let me know if I can release it to a (very small) batch of participants for testing

**Comment by HenryMehta** [comment]
I don't know why but for some reason the study wasn't updated as part of the migration process to use the split forms so was getting confused.

Do you have another split form one that was live before this morning so I can see if that updated.  I ask because I can see some have

**Comment by HenryMehta** [comment]
@JMankewitz  Please go ahead and release.  The issue is it hadn't been assigned a split demographics form for some reason.  I can see others have so I don't know why this didn't but I added it through admin and it is fine now

**Comment by HenryMehta** [comment]
I'll stay online while you're running a small sample just in case

**Comment by JMankewitz** [comment]
It looks like my previous studies are working just fine. Thanks for the quick response! I'll rerelease and monitor just in case

**Comment by HenryMehta** [comment]
@JMankewitz Do you have any non-split demographic studies - are they working.  I think those are ALL erroring.  I need someone else to confirm
