### ISSUE TITLE
Value for the word "country" is appearing as "Canada" for Canadian English CDI

### ISSUE THREAD

**Issue by hilary-rose** [langcog/web-cdi#318]
Hi there,

We noticed today that the output value for knowing the word "country" is being exported as "Canada" instead of "understands" or "produces" for the Canadian English CDI (Words and Sentences). I think the column name matches the column name for the demographics section, so maybe that has something to do with it? Once this is fixed, will there be a way of getting the original answer to the question back?

Thank you for looking into this!

**Comment by hilary-rose** [comment]
@HenryMehta Has someone been able to look into this yet? Thank you!

**Comment by HenryMehta** [comment]
@hilary-rose I'm really sorry I haven't yet - I hope to get to it next week

**Comment by HenryMehta** [comment]
@hilary-rose
I'm deploying a fix to development now - I think you have access so could you give it a quick test and confirm.
Also, while correcting this I noticed that the split demographic forms are not working for you.  I've also corrected that but could you test and confirm it is right and I've not missed anything normally in your forms.  You will need to create a new study for this and then select English_split from the Demographic dropdown in the New Study modal.

@vmarchman I think the country error is also and issue for Korean and I've emailed and asked them to confirm

**Comment by hilary-rose** [comment]
Hi @HenryMehta, I tested the development version and it seems to work now, thank you!
