### ISSUE TITLE
Centiment CDI Background changes

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#328]
Hello!
We have a couple changes to the background additional questions for the Centiment CDI background:

* The label "Parental Attitudes" to "Your Feelings on Parenting"
* "Literacy" to "Things That You and Your Family Do"
* We'd like to make the "Parental Attitude" questions (now "Your Feelings on Parenting") required.

**Comment by JMankewitz** [comment]
This is higher priority and lower global impact, so lets focus on this one. 

Thanks!

**Comment by HenryMehta** [comment]
@vmarchman @JMankewitz 
I've made the changes and tested locally and in development.  With that in mind I've also put to production but please run a quick test through development to ensure you're happy before using in production.
