### ISSUE TITLE
instructions for CDI

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#33]
above demographics in first screen of the survey, we want to have the instructions that are on the instrument itself

**Comment by mcfrank** [comment]
e.g. from word document from @vmarchman

**Comment by mcfrank** [comment]
And also a header that says "MacArthur-Bates Communicative Development Inventory" and a link with "Click here for more info" to mb-cdi.stanford.edu

**Comment by mikabr** [comment]
does the document with the instruction text exist somewhere?
