### ISSUE TITLE
Add Argentine Spanish Forms

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#335]
We would like to add Argentine Spanish Long Forms.  Contact person is Mariela Resches mresches@gmail.com.  She has an account and access to the Mexican Spanish forms for exploring the system.  @HenryMehta Can you please direct her to the Mexican Spanish files so that she can edit for use with Argentine Spanish.  Thanks!

**Comment by HenryMehta** [comment]
@vmarchman Just to let you know I've now started on this
