### ISSUE TITLE
redirect button error

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#336]
@HenryMehta @JMankewitz 

Hello, 

My name is Kellan Kadooka, I am a researcher at the University of California, Riverside. We have been notified from our participants using the WebCDI that the "redirect button at the completion of study" returns the error message:
Not Found
The requested resource was not found on this server.

Upon looking at our WebCDI interface for the study it appears that although there is a valid url to Google Form where we are collecting some additional information, the redirect button is not redirecting. 

Any insights to the issue or suggestion of fixing the problem would be greatly appreciated.

Thanks,
Kellan Kadooka

--
Kellan Kadooka, M.A.
PhD Student
Perception Action and Development Lab
University of California, Riverside

**Comment by HenryMehta** [comment]
@vmarchman @JMankewitz 
I'm deploying a fix to development.  Would you like to test or shall I  put straight to production?
Henry

**Comment by JMankewitz** [comment]
I've tested on dev and all looks good! All clear for pushing to prod
