### ISSUE TITLE
Generalizing set up for new sources

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#352]
Hello! 

We're adding redcap as a possible source for the single reusable link with URL parameters. These are the following changes that should be made, at a minimum:

- [ ] Add RedCap as a Participant source (in addition to None, Prolific, and Centiment
- [ ] Change "Prolific Link:" on the administer new subjects pane to "External Source Link:"
- [ ] Update the Prolific Link blurb to be more general, swap out "Prolific Id" for "External Link ID (e.g., Prolific ID, Worker ID)"

However, we have a couple other requests/suggestions that will make things much cleaner for _any_ researcher who wants to hook webcdi into an external vendor (eg prolific, Centiment, lookit, mturk, redcap, basically anything with a url parameter and redirects).

Redirect URLS

- Currently the text is "Enter a basic return URL - the Centiment aid will be added automatically". This may be confusing for people who are using the redirect URL for other vendors. Either we should drop the " - the Centiment aid will be added automatically" completely OR we should add a function for appending the source ID with a **user defined** url parameter key. 
    - So for example, the setup prompts would be: 
        - Participant Source: `Centiment`
        - Provide redirect button at completion of study? `T`
        - Please enter redirect URL: `centiment.com/survey_code`
        - Append source_id to redirect URL? `T`
        - URL parameter key: `aid`
    - Would redirect to `centiment.com/survey_code?aid=source_id`

Defining Participant Source

- We should ideally allow users to add their own sources, so the options should be:  
    - None
    - Prolific
    - Centiment
    - RedCap
    - Other (fill)
- We still want to provide as many options as possible so the data are consistent across users for specific sources, but we also want to be flexible if people are building their own links to us outside of Prolific and Centiment 

Let me know if there are any questions about the plan, here! Thanks, Jess

**Comment by JMankewitz** [comment]
We've also gotten a request to add Lookit as a url source so the participant/sourceID from lookit is shared with webcdi. 

At a minimum, we'd like users to use the sources Lookit, Redcap, Prolific, and Centiment. A major, but small, upgrade would be to show the Source ID (e.g., prolific_id, lookit subject ID, centiment aid but labeled "Source ID") on the page where users can see their in progress/completed data per subject. This can be blank/NA for studies where no source ID is used.

**Comment by HenryMehta** [comment]
@JMankewitz HI Jess, I'm going to start on this as soon as the Argentine is signed off and live - I don't want to mix the code

**Comment by JMankewitz** [comment]
Thank you, let me know if you have any questions about the use cases etc!

**Comment by HenryMehta** [comment]
@JMankewitz 

These were really well written requirements - thank you.  I think I've understood them and implemented correctly.

I'm deploying my first effort at this to dev now.

Note: I haven't done any work to convert existing  Centiment studies.  I can if you want but currently, when this goes live researchers would need to log into the Centiment study and update the relevant fields.

**Comment by mcfrank** [comment]
@mekline was interested in discussing this on the lookit side.
