### ISSUE TITLE
need "download administration info" link

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#36]
so that researchers can download the full csv with the links etc. of the stuff that shows up in the researcher interface

**Comment by mcfrank** [comment]
this is for purposes of keeping track of links etc.

**Comment by mikabr** [comment]
The downloaded file is named a bit wrong (seems to be `studyname_-data.csv_`).

**Comment by bengittelson** [comment]
I'm having a different problem with the name of the downloaded file; it gives me studyname--data.csv-.

**Comment by bengittelson** [comment]
I fixed this so that the files are now named studyname_data.csv.
