### ISSUE TITLE
English text in background questions instead of Dutch

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#363]
In both the background questions of WG and WS there is sometimes English text instead of Dutch. 
Specifically at these questions:
- question about language/developmental problems; if you tick yes it says "please describe" instead of "Leg uit"
- question about which caregivers live with the child; if you choose other caregivers it says "please specify" instead of "Leg uit"

**Comment by HenryMehta** [comment]
@Cielke-Hendriks I hope you're well.  I'm just deploying this change now - should be available to check in 20 minutes or so

**Comment by Cielke-Hendriks** [comment]
@HenryMehta do I have to check this in the test_upgrade user? If so, the problem with the language/development problems seems solved. The issue with the caregiver question is still there.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks I'm not seeing anything in English (so probably looking in the wrong place).  Could you add a screen shot so I can see exactly where the issue is please.  Thank you

**Comment by Cielke-Hendriks** [comment]
@HenryMehta  Here is the screenshot, hope this helps. 

![English text Dutch CDI](https://user-images.githubusercontent.com/43846987/143854467-89fd2827-824f-44c3-a706-6c2c199b6343.png)

**Comment by HenryMehta** [comment]
Thanks @Cielke-Hendriks, found it and fixed it (finally).  It was actually not working on all languages but you're the only person to find it.  Please check and confirm working ok now.  Thank you

**Comment by Cielke-Hendriks** [comment]
@HenryMehta, Yes it is working now. Thank you.
