### ISSUE TITLE
Quebec French form - grams are incorrect for birthweight options

### ISSUE THREAD

**Issue by hilary-rose** [langcog/web-cdi#364]
Hi there, we noticed that a few of the options on the Quebec French CDIs (both forms) for the birthweight question have incorrect weights in grams. The ones that need correcting are as follows (this is the corrected text):

8 lbs, 8 oz - 8 lbs, 15 oz (3856 grammes - 4081 grammes)
9 lbs, 0 oz - 9 lbs, 7 oz (4082 grammes - 4308 grammes)
9 lbs, 8 oz - 9 lbs, 15 oz (4309 grammes - 4534 grammes)
10 lbs, 0 oz ou plus (4535 grammes ou plus)

The English forms seem to be okay. Is this a relatively quick/easy thing to fix?

Thank you!

Hilary

**Comment by HenryMehta** [comment]
@hilary-rose 
Hi Hilary, I'm deploying a fix to the development environment.  Could you confirm it has worked please?  Thank you

**Comment by hilary-rose** [comment]
Hi Henry, I just took a look and both Quebec French forms look good now! Let me know when the changes have been pushed to the live site. Thank you!

**Comment by HenryMehta** [comment]
@hilary-rose I think this is now live.  Could you confirm for me.  Thank you
