### ISSUE TITLE
change wording for CAT-CDI

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#375]
@HenryMehta We want to change the wording in the question for parents to:

"Does your child say...."

rather than

"Can you child say...."

@kachergis What is the wording for Spanish?

**Comment by HenryMehta** [comment]
@vmarchman 
I'm deploying to development now.
We don't currently provide anything except an English version of CAT.  The code isn't there to do multiple languages

**Comment by kachergis** [comment]
@vmarchman it's more a question for @HenryMehta -- I can give him the final parameters for the Spanish CAT, so I imagine it's fairly straightforward to adapt the English CAT template for use with the Spanish items, but may take a couple hours and require a bit of testing?

**Comment by HenryMehta** [comment]
I think it might be a little longer than 2 hours.  The current API for the cat is written for English only.  It would need amending  to take multiple languages which then also means the API calls from WebCDI will need amending.  We currently only have a production version of the CAT API so we would need to 
1. create a development version,
2. have the development WebCDI point at the development CAT API.
3. amend the API to handle multiple languages and import the Spanish data
4. amend WebCDI to call Cat API according to the new API structure
5. Test both English and Spanish to ensure working
6. Deploy

Probably more like a couple, possibly three, of days I think

**Comment by vmarchman** [comment]
@HenryMehta Let's hold off on the Spanish for now.  We will make CAT more flexible wrt other languages (e.g., French) and then build Spanish in that process

**Comment by HenryMehta** [comment]
@vmarchman I am reopening this until the text change is in production

**Comment by vmarchman** [comment]
Got it.  Sorry - I got ahead of myself!  It looks good to me @Henry
***@***.***>

**Comment by HenryMehta** [comment]
yes, just waiting on lookit to be signed off

**Comment by vmarchman** [comment]
Ahhh. Ok.

@George Kachergis ***@***.***> What do we need to do to
build a CAT in Spanish?

**Comment by kachergis** [comment]
Hi @vmarchman, I've already modified the API to load the Spanish parameters and handle requests for the Spanish (production) CAT (Henry's step 3 above, and he has done the other steps for English and now French). The remaining pieces are 1) translation of the carrier phrase and any other special instructions to be given for the CAT, and 2) adding/checking disambiguation. I know I asked for Paulina's help with that quite some time ago, but looking through old emails I'm not sure it was ever completed -- I can ping her to double-check (I may have misplaced it..). Are people eager for it? ^^
