### ISSUE TITLE
Percentile look up for English short forms

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#387]
Add look-up functionality for English Level 1A and Level 2A and B

**Comment by HenryMehta** [comment]
@vmarchman Are these the norm data files you sent me which are in #398?

**Comment by HenryMehta** [comment]
@vmarchman I have assumed the files from #398 are the ones I require.  These are now loaded and ready to test

**Comment by vmarchman** [comment]
@Henry ***@***.***>  Starting with testing the short form
benchmarking. Thanks!

I like the dropdown in the download data section.  And, it looks like the
computation of Adjusted Benchmark age is working. :-)

But, when I download the excels, I get the exact same output for both
choices: "Download Data" and "Download Data with Adjusted Benchmarks."   It
seems like both are the latter choice.

And, only the "by sex" adjusted percentiles are being populated - Not the
"both" ones.

How about Download Data gives the original columns, basing everything on
the Benchmark Age (chronological) age.  So, if you don't have any premie
kids, you would just choose this option.

Understands
Understands-percentile-sex
Understands-percentile-both
Produces
Produces-percentile-sex
Produced-percentile-both.

But, the Download Data with Adjusted Benchmarks" gives those same columns,
plus the -adjusted ones. In this case, if you knew you had premie kids, you
would get BOTH sets of percentiles, ones against the chronological age and
one against the adjusted age.

Understands
Understands-percentile-sex
Understands-percentile-sex-adjusted
Understands-percentile-both
Understands-percentile-both-adjusted
Produces
Produces-percentile-sex
Produces-percentile-sex-adjusted
Produced-percentile-both
Produced-percentile-both-adjusted

Also, I think we can get rid of the last two choices in the dropdown (CDI
Scoring program and Data Dictionary) - I'll make a new issue.

Thanks!

**Comment by HenryMehta** [comment]
@vmarchman I think combines is now fixed and ready to test
