### ISSUE TITLE
Development of CAT to other languages (FRENCH)

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#391]
Based on #375, referencing Spanish, the steps are: 

The current API for the cat is written for English only. It would need amending to take multiple languages which then also means the API calls from WebCDI will need amending. We currently only have a production version of the CAT API so we would need to
1. create a development version,
2. have the development WebCDI point at the development CAT API.
3. amend the API to handle multiple languages and import the Spanish data
4. amend WebCDI to call Cat API according to the new API structure
5. Test both English and Spanish to ensure working

We need to do this for French, and then Spanish.  @kachergis  has the data for French that you need @HenryMehta

**Comment by vmarchman** [comment]
Per @kachergis you should already have the parameters that you need to get started.  Is that correct @HenryMehta ?

**Comment by kachergis** [comment]
@HenryMehta  I added you to the repo (CDI-CAT-FR), which has the IRT item parameters for French in the same format as we used for English. Note that we will replace the definitions currently in the CSV file with the cleaned, disambiguated item definitions from Sho's team, once they finish doing that.

**Comment by HenryMehta** [comment]
@kachergis @vmarchman 
I spent a couple of hours looking at this today.  I really wanted to get to the point of having multiple language ability even it only 1 there.
But my R is not good enough.
At the moment we have a single database and query that for the data we want.  All in English.  
We need to have a single database with the different languages available and based on the call run the functions to get the relevant next word.
I don't know if George's R is sufficiently good to explain how I should do this?

**Comment by HenryMehta** [comment]
@kachergis @vmarchman @JMankewitz 
I have run through the test sequences and these are the results:

- EN theta 0:  Goes from ball to leg after first response FAIL
- EN theta 1: Goes from street to talk after 16th response FAIL
- FR Theta 0: Finishes at se.dépêcher FAIL
- FR Theta1: PASS
- SP Theta0: PASS
- SP Theta1: PASS

It should be noted, the English results in production are the same as dev

I cannot remember how we got this sorted last time George

**Comment by vmarchman** [comment]
Ok - @***@***.*** ***@***.***> @George Kachergis
***@***.***> It looks like there's some fails for the
French - which is unfortunately, the one that we are waiting the most for.
Any chance we could resolve soon?  Or should I let them know we need to
postpone delivery?  @Michael C Frank ***@***.***> ?
