### ISSUE TITLE
allow for different benchmark ages (adjusted age) for percentile look up

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#397]
Right now, all percentile scores are computed in reference to the actual child's age based on date of test and date of birth as computed in the background information form.  This "benchmark age" is the child's chronological age.

For children born preterm, it would be great to be able to get percentiles based on the child's "corrected" age, i.e., the age they would be if they were born at term, rather than when they were actually born.  

To compute corrected/adjusted age, you take the chronological age and subtract the number of weeks born premature.  For example, a child who is 18 months chronological age, but who is born 4 weeks early, would have the benchmark age be their adjusted age of 17 months (rather than 18 months), so 1 month early.

In the demographics form, we ask: Was your child born early?  If so, how many weeks?  

Anyone who is born 1-3 weeks early, would be compared to their chronological age, but anyone who is born:

4-7 weeks early, would be compared to kids 1 month younger, i.e., chron age - 1 month
8-11 weeks early, 2 months younger, i.e., chron - 2 months,
12-15 weeks early, 3 months younger, i.e., chron - 3 months,
16+ weeks early, 4 months younger, i.e., chron - 4 months    

It would be great if the user could get both sets of percentiles when they download the scores/percentiles, as folks would want to see the percentiles for chronological age (how is the kid doing relative to peers of their same chron age) AND adjusted age (how is the kid doing relative to kids who are their same adjusted age).   

I see two options: (1) We automatically, generate both percentiles for every child, for every download.  That is there would be two sets of percentiles, one set compared to "benchmark age" chronological and one benchmark age as "adjusted."  For most kids the two sets of percentiles would be the same, since the kids are not born early.  Pro: You always get it; Con: Most people won't need it and it adds a bunch of stuff that people don't want most of the time.

The second option is to have users opt into this option in the user interface at the study level, that is, select a button that says, add benchmark age for adjusted age? Yes/No  The user could toggle this option on/off.  Most users won't want it, but others will want it in all cases.

Thoughts @HenryMehta ?

**Comment by HenryMehta** [comment]
@vmarchman 
I've set up two download buttons, one with adjusted ages and one without.  For it to work we need to recalculate all the summary scores.  This takes about 18 hours.  I've started it running but it will be a while

**Comment by HenryMehta** [comment]
Virginia's comments entered in wrong issue.  They are here: https://github.com/langcog/web-cdi/issues/387#issuecomment-1226635825

**Comment by HenryMehta** [comment]
@vmarchman 
The percentiles weren't showing because I had or didn't have a space between the category and the word percentile, so it wasn't matching the row name.
This is now sorted but it means I need to rerun scoring which I'm doing now.  It takes about 12-18 hours (assuming it doesn't crash).  So if you look in the morning you may seem some results.  By the evening, it should be available

**Comment by vmarchman** [comment]
@Henry ***@***.***>  For both WG Level I and WS Level IIA - the
"both" percentiles are not propagating in either the unadjusted or the
adjusted outputs.

**Comment by HenryMehta** [comment]
@vmarchman deploying a fix now.  Plus I need to update the scores which takes 12-18 hours to run so it will all be available then
