### ISSUE TITLE
Update lookup tables for English long and short forms

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#398]
After the 2020 renorming, we now have new percentile tables for all of the English long forms (WG and WS) and English short forms (Level I, Level IIA, Level IIB) and CDI III.  

These numbers will need to be populated into the look-up tables for Web-CDI.

@HenryMehta

**Comment by HenryMehta** [comment]
@vmarchman Can you provide me with the new percentile tables

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> The new tables are attached.  Let me know if
you have any questions!

**Comment by HenryMehta** [comment]
@vmarchman We don't currently have benchmarking for short forms.  Can you tell me which forms I should be adding it to.  Thanks

**Comment by HenryMehta** [comment]
Also, within WS we seem to have lost Combining, and added Word Forms and Word Endings.  I need to match these up to titles within the Scoring.  Likely candidates are

 ```
{
        "title" : "Word Endings 1",
        "category" : "word_endings_1",
        "measure" : "sometimes;often",
        "order" : 3
    },
    {
        "title" : "Word Forms 1 Nouns",
        "category" : "word_forms_nouns_1",
        "measure" : "produces",
        "order" : 4
    },
    {
        "title" : "Word Forms 1 Verbs",
        "category" : "word_forms_verbs_1",
        "measure" : "produces",
        "order" : 5
    },
    {
        "title" : "Word Forms 2 Nouns",
        "category" : "word_endings_nouns_2",
        "measure" : "produces",
        "order" : 6
    },
    {
        "title" : "Word Forms 2 Verbs",
        "category" : "word_endings_verbs_2",
        "measure" : "produces",
        "order" : 7
    },

If they are a combination of any of these, then we need to amend the scoring file.

I have no idea what WSM3L is.  Also, these are not integer values so I don't know if they'll work
```

**Comment by HenryMehta** [comment]
@vmarchman Also, within WS we do not have scoring for Word Endings or Word Forms.  We need to add these to scoring before the benchmarks can work.  I will apply some scoring and we'll see if I get it right

**Comment by HenryMehta** [comment]
@vmarchman for WS I've used Word Endings 1 and Word Forms 1 Nouns.  I did this rather than creating new categories because new categories will require the scoring to be rerun.  If I have to do that, it ok, but I don't want to do it and then redo it because I selected the wrong categories because the rerun takes circa 12 -18 hours

**Comment by HenryMehta** [comment]
@vmarchman available to test

**Comment by vmarchman** [comment]
There are new tables for English CDI III as well 
[IIIcomplex_both.csv](https://github.com/langcog/web-cdi/files/11274394/IIIcomplex_both.csv)
[IIIcomplex_boys.csv](https://github.com/langcog/web-cdi/files/11274395/IIIcomplex_boys.csv)
[IIIcomplex_girls.csv](https://github.com/langcog/web-cdi/files/11274396/IIIcomplex_girls.csv)
[IIIprod_both.csv](https://github.com/langcog/web-cdi/files/11274397/IIIprod_both.csv)
[IIIprod_boys.csv](https://github.com/langcog/web-cdi/files/11274399/IIIprod_boys.csv)
[IIIprod_girls.csv](https://github.com/langcog/web-cdi/files/11274400/IIIprod_girls.csv)
[IIIuselang_both.csv](https://github.com/langcog/web-cdi/files/11274401/IIIuselang_both.csv)
[IIIuselang_boys.csv](https://github.com/langcog/web-cdi/files/11274402/IIIuselang_boys.csv)
[IIIuselang_girls.csv](https://github.com/langcog/web-cdi/files/11274403/IIIuselang_girls.csv)

**Comment by HenryMehta** [comment]
@vmarchman I need to understand how these refer to CDI3 scoring.

The scoring json looks like this:

```
[
    {
        "title" : "Total Produced",
        "category" : "word",
        "measure" : "produces",
        "order" : 1
    },
    {
        "title" : "Combining",
        "category" : "combine",
        "measure" : "sometimes;often",
        "order" : 2
    },
    {
        "title" : "Complexity",
        "category" : "complexity",
        "measure" : "complex",
        "order" : 3
    },
    {
        "title" : "How to Use Words",
        "category" : "usage",
        "measure" : "yes",
        "order" : 4
    },
    {
        "title" : "Combination Example 1",
        "category" : "combination_example1",
        "measure" : "complex",
        "order" : 10,
        "kind" : "list"
    },
    {
        "title" : "Combination Example 2",
        "category" : "combination_example2",
        "measure" : "complex",
        "order" : 11,
        "kind" : "list"
    },
    {
        "title" : "Combination Example 3",
        "category" : "combination_example3",
        "measure" : "complex",
        "order" : 12,
        "kind" : "list"
    }
]
```
Could you confirm complex is Complexity, prod is Total Produced and uselang is How to Use Words.  Thanks

**Comment by HenryMehta** [comment]
@vmarchman Also, the ages on CDI3 look very very strange.  They seem to be 1-4 months

**Comment by HenryMehta** [comment]
@vmarchman CDI3 benchmarks now loaded and tested.  You will need to created and complete a new administration to see the data
