### ISSUE TITLE
backup 

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#4]
@vmarchman will help Ashwin set up a recurring job on the lang learning lab H&S server to pull the database to lab server?

**Comment by mcfrank** [comment]
didn't work, new method? clone to second ec2box?

**Comment by ranjaykrishna** [comment]
If your main aim is to just backup versions of the database, I recommend using Amazon's S3 buckets. They are really cheap since they have slow IO, which is not something you care about for a backup system.

**Comment by mcfrank** [comment]
thanks Ranjay!

Mike

**Comment by mcfrank** [comment]
Looks like we want to make a cron job that zips up the whole sucker and then runs:

https://boto3.readthedocs.org/en/latest/reference/services/s3.html#S3.Client.upload_file

to the S3 bucket I just created called web-cdi-backup

**Comment by mcfrank** [comment]
correction - no need to zip anything. we will use boto's sync method

http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by mcfrank** [comment]
https://gist.github.com/andrewschoen/1732726

**Comment by mcfrank** [comment]
done through S3, thanks @daniellekellier
