### ISSUE TITLE
fix typos on Spanish Level 1 and Level 2 short forms

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#415]
On Level I: 

Item says "two" -> should be "uno dos tres"
mio should be mío

On Level II:

These items have spelling/accent errors:

quiruiriqui should be quiquiriquí
vibora should be víbora
periodico should be periódico
oir should be oír

**Comment by vmarchman** [comment]
@HenryMehta If it is easier, please let me know what files I should edit and I can make the changes.

**Comment by HenryMehta** [comment]
@vmarchman I am deploying this now so should be available for you to test when you get up.  If you confirm it is working I'll deploy to production
