### ISSUE TITLE
sharing opt out

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#426]
Those users/researchers who PURCHASE the forms distributed by Brookes (English/Spanish WG and WS, CAT) can opt out of data sharing at the Study level.  That is, because they have purchased the right to use the forms (as opposed to get them for free), they are NOT obligated to share their data with us.  They can if they want to, but they are not obligated to and may want to do so for some studies, but not others. So, we need an option at the Study level that says "All data collected within this study will not be available for broader sharing" YES/NO.  In that case, all administrations in that study would default to YES on "opt out of broader sharing".   Those who would like to share data in a given study will still have the option to opt out at the administration level (i.e., should a particular participant not give permission to share).

We could THEN make the script for downloading the data AUTOMATICALLY screen out participants with the "Opt out" column as YES. (Right now, the column is there and we just delete the relevant data after downloading).

**Comment by HenryMehta** [comment]
@vmarchman How do you currently download the data?  Is this from admin or using the download function on the Study as a the researcher?

I am assuming you want something in admin.   

And with that in mind, should the scoring data and scoring summary functions available in admin be amended to exclude opted out administrations?

**Comment by vmarchman** [comment]
@Henry ***@***.***>  I use the download options from within Admin.
The opting out of sharing functionality would be from admin.  Opting out
would not change how an individual researcher accesses their own data.  So,
it could be just a flag on the studies/administrations so that the admin
would know not to include those data in any sharing.

If it's easy to make it dummy proof so that those administrations are
automatically deleted when the admin downloads the data, that would be
fine.  But, it's also fine just to put a flag in the opt out column and
assume that the admin will delete those data in a first step.

**Comment by HenryMehta** [comment]
@vmarchman deploying to dev now.

Researchers can set a study to opt out of data sharing.  They can do this whether the study chargeable or not BUT it only applies a filter on chargeable studies.  The help text makes this clear.  I thought this would give you additional information that may be useful.

Within admin I show you the researchers opt out preference and if it is a chargeable instrument so whether it matters.  But I also prevent download of data from opted out studies and I am not filtering out opted out administrations within the download

**Comment by vmarchman** [comment]
@Michael Frank ***@***.***> Do we want to give ALL folks (whether
they pay or not) the option to opt out of data sharing at the STUDY level?
We give them the option to opt out at the administration level, e.g., if a
parent doesn't sign the consent to share.  But, should "free" instruments
be able to opt out of data sharing at the study level?

**Comment by vmarchman** [comment]
@Henry ***@***.***> @Michael Frank ***@***.***>  My
inclination is to say that ONLY folks who are paying can opt out at the
study level.  That's the "cost" of using the tool.

**Comment by HenryMehta** [comment]
@vmarchman ok, I've made some amendments.  The opt out is now only editable for chargeable instruments and cannot be updated once the study has been created
