### ISSUE TITLE
demographic opt out - related to Issue #426

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#427]
If a researcher has purchased the forms from Brookes (English/Spanish WG and WS, English/Spanish CAT), they an opt out of broader sharing (issue #426) but then ALSO then choose to omit the demographic questionnaire (EXCEPT for DOB, child SEX, and (possibly) "who is filling out this form".)

This option would be available ONLY for those folks who choose not to share their data at the Study level.   This option would need to be clearly visible BUT grayed out and with some kind of warning that says “this option only available for premium users who have opted out”.

**Comment by HenryMehta** [comment]
@vmarchman Does this mean they can choose to not share demographic information, but would share the remaining data, or does this mean they don't need to collect the data?

**Comment by vmarchman** [comment]
@Henry ***@***.***> It means that they can opt out of collecting
the data via Web-CDI.  They must collect the demographic data (along with
the instrument data) IF they are using free/non-chargeable forms.

On chargeable forms, users can opt to collect the demographic data within a
single study or not, BUT if they have opted in to sharing the data, they
MUST collect the demographics.

So, the opting out of collecting the demographic data is ONLY available on
(1) chargeable forms, and (2) on folks who have opted out of sharing the
data, i.e., only for “premium” users who have opted out of data sharing.
Maybe need to have that option clearly visible BUT grayed out and with some
kind of warning that says “this option only available for premium users who
have opted out of data sharing”?

**Comment by HenryMehta** [comment]
@vmarchman Deployed to dev and ready to test

**Comment by vmarchman** [comment]
That looks great!  Wonderful!

one thing @HenryMehta We should add to the demographic questions the prematurity questions.  Otherwise, they won't be able to do the corrected scoring by age to compare.....Or, can we toggle that question on and off?

**Comment by HenryMehta** [comment]
@vmarchman added prematurity questions and deploying now - toggle is difficult and I'm now beginning to worry about time because of the other items being bigger than I thought

**Comment by vmarchman** [comment]
Not toggling is fine
