### ISSUE TITLE
submission should pop-up a "thank you" modal

### ISSUE THREAD

**Issue by mikabr** [langcog/web-cdi#43]

**Comment by daniellekellier** [comment]
I think we should write a thank you letter. I remade the printable CDI page to look like this on my local copy of the server. So we can have a giant thank you, then a thank you letter (perhaps even a signature and a logo), then a button which can take them to the Shiny results app. In addition, there is a "show me my answers" link which displays their saved data (it's in a collapsible panel)

![screen shot 2016-11-07 at 11 49 01 am](https://cloud.githubusercontent.com/assets/19960439/20073295/87a13372-a4e0-11e6-8173-1e8eacc72564.png)
![screen shot 2016-11-07 at 11 51 01 am](https://cloud.githubusercontent.com/assets/19960439/20073296/87a748de-a4e0-11e6-8800-5df759f5cea7.png)

**Comment by daniellekellier** [comment]
I turned printable_cdi.html into a page with a short thank you letter, Mike's signature, and 2 collapsed panels of the R shiny results app and their completed form.

![screen shot 2016-11-07 at 3 23 02 pm](https://cloud.githubusercontent.com/assets/19960439/20080401/64cc615a-a4fe-11e6-82bf-0dcc748e7cbe.png)

![screen shot 2016-11-07 at 3 23 30 pm](https://cloud.githubusercontent.com/assets/19960439/20080419/7c29e6b0-a4fe-11e6-8b7a-7c243a726a64.png)

![screen shot 2016-11-07 at 3 23 20 pm](https://cloud.githubusercontent.com/assets/19960439/20080406/6d6bef24-a4fe-11e6-993b-2565e5a2abc7.png)

**Comment by mcfrank** [comment]
That's starting to look really nice!

Mike
