### ISSUE TITLE
English text in Spanish Mexican CAT

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#438]
@HenryMehta The instructions on Page 1 and on the final splash page of the Mexican Spanish CAT are in English.

Instead of:
Instructions for completing the language inventory
In this survey, we ask you about words that your child “says” in English.
Try to complete the survey when you have a few quiet minutes, without interruptions. An example might be when your child is sleeping.
Don’t worry! Your child does not need to pronounce the words exactly as you do (e.g., “raff” instead of “giraffe”). And there might be some words in your family that you use instead (e.g., “nana” for “grandma”).
Remember, these words are just some of the words that a child might say, so it is ok if they do not say all of them!

Should be:

Instrucciones para completar el inventario del lenguaje.

Marque las palabras que su hijo(a) COMPRENDE Y DICE en ESPAÑOL.

Cuando tenga por lo menos 10 minutos tranquilos sin interrupciones, trate de llenar el inventario. Un ejemplo 
podría ser cuando su niño(a) este durmiendo.

Marque las palabras aunque su hijo(a) las pronuncie de manera diferente; por ejemplo, si dice “tatamina” en vez de “vitamina” o “papo” en vez de “zapato”.

Marque las palabras que sean diferentes, pero que tienen el mismo significado que las que vienen en el inventario. (Por ejemplo, si su hijo(a) dice “coca” en vez de “refresco”, o “súper” en vez de “tienda”.)

Recuerde, estas palabras son solo algunas de las palabras que un niño podría decir, ¡así que está bien si no las dice todas!

and 

"Thank you for filling this out! Of the words we asked, the hardest word your child knows is "dedo" and the easiest word is "agua".

Should be: 

"¡Muchas gracias! De las palabras que pedimos, la palabra más difícil que su niño(a) dice es "XXXX" y la palabra más fácil es "XXX".

**Comment by HenryMehta** [comment]
@vmarchman deployed to dev for testing

**Comment by vmarchman** [comment]
Perfect! Thanks!
