### ISSUE TITLE
Email Validation for new registration

### ISSUE THREAD

**Issue by HenryMehta** [langcog/web-cdi#441]

**Comment by HenryMehta** [comment]
And make Researcher Login to User Login and Blue.  
And move admin to button on researcher menu.

**Comment by HenryMehta** [comment]
@vmarchman I have made and deployed these changes to dev

**Comment by vmarchman** [comment]
@HenryMehta Looks great, but three small things: (1) my mistake, but it should be https://brookespublishing.com/product/cdi (not products)

(2) can we add the email address to the "contact the webcdi team" webcdi-contact.stanford.edu

(3) the email validation seems to work, but when you register, you get this message something like: "thank you for registering.  The Web-CDI team will review your registration and get back to you within several days." 

Can we change to something like: "Thank you for registering for Web-CDI.  An email was sent to the address you provided.  Please click on the link in that email to complete your registration."

**Comment by HenryMehta** [comment]
@vmarchman deploying to dev now.  Should be there in 30 minutes
