### ISSUE TITLE
very minor: add webcdi name/logo to the upper left hand corner of the window

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#443]
Otherwise when you have a window open, you can't tell what app you're in. :)

**Comment by HenryMehta** [comment]
@mcfrank Which window?

**Comment by mcfrank** [comment]
something like this?
[image: Screenshot 2023-05-11 at 10.06.27 AM.png]

**Comment by HenryMehta** [comment]
@mcfrank because you've replied to the email, I cannot see the screenshot.  You need to click on the Github link at the bottom of the message and send again

**Comment by HenryMehta** [comment]
@mcfrank this has been changed in the new development.  Take a look at dev
