### ISSUE TITLE
better way to add users to mailing list

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#444]
Right now, I have to manually add users to the Webcdi-users@stanford.edu mailing list from the list of users in Web-CDI.  This is a pain and subject to error.  When I was onboarding each person, this was manageable, but now that people can register on their own, it's harder to keep track and people get missed.

Possible solutions:

(1) Send me an email with each new user added
(2) Add date of user created to the list in admin so that I can sort by that and get only the newly joined users.  I can do this before each big user email (since they don't happen that often - except recently).
(3) Have the list managed within Web-cdi, rather than through Stanford mailing lists - but there are junk users in the system, so I don't know if that will be a pain

Thoughts @HenryMehta ?

**Comment by HenryMehta** [comment]
I can create an admin action which allows you to download user emails.  Would that work?

**Comment by HenryMehta** [comment]
Do you need this before golive or can I do next week?

**Comment by vmarchman** [comment]
Next week after we go live is fine!!!
