### ISSUE TITLE
CAT scoring

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#448]
@HenryMehta The CAT norming tables are set up just like the other tables that we have with Males, females, and both.  You would need to sort them so that 99th is at the top and 5th is at the bottom.  And in the period of 16-18 months, the numbers are pretty similar.  For kids who are 12-15 months, they get a percentile based on the WG norms, for kids 16+, they get a percentile based on the WS norms. (edited) 

Note to self: One thing that is funny is that they are negative numbers (rather than bounded by a lower end of 0).  But more negative is worse, so younger kids and kids with lower percentiles have more negative numbers.  So, I think that's ok.

The link to the tables are here: 

English: https://github.com/langcog/CDI-CAT-EN/tree/main/norms
Spanish: https://github.com/langcog/CDI-CAT-SP/tree/main

**Comment by vmarchman** [comment]
@HenryMehta CAT scoring seems to be working fine for me now

**Comment by HenryMehta** [comment]
@vmarchman I think this has actually been put live with the API stuff a couple of weeks ago.  Do you have a production CAT to check ?

**Comment by vmarchman** [comment]
@Henry ***@***.***> Ok - I can test on prod

**Comment by vmarchman** [comment]
@HenryMehta Yes - this works on prod.  There are extra columns that would be good to delete from the outputs, but the important thing is that the percentile scores and raw values are there.
