### ISSUE TITLE
new records automatically populating

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#455]
Two people have reported that new participant records are automatically being created.

![image](https://github.com/langcog/web-cdi/assets/7682636/4b527789-e72d-40bb-8139-1243c5039225)

**Comment by vmarchman** [comment]
One person reported that this happened when they selected a particular record and said "readminister participants."

the other person though I don't think did that and now many thousands of new records were created.

**Comment by HenryMehta** [comment]
Readaminister participants has always done this, creating new administrations for the same participants.  I don't understand the issue

**Comment by vmarchman** [comment]
It creates all participants even those not clicked

**Comment by vmarchman** [comment]
Sounds like it was user error.
