### ISSUE TITLE
Limit the number of new records that can be created

### ISSUE THREAD

**Issue by HenryMehta** [langcog/web-cdi#456]
Someone created 123456 new records which weren't wanted.  We need a max number installed

**Comment by vmarchman** [comment]
@HenryMehta Perhaps also have a confirmation question:  e.g., You are about to add XXXX number of new administrations to your study.  Do you want to continue?

**Comment by HenryMehta** [comment]
@vmarchman deployed to dev.  I've set the maximum value to 100

**Comment by vmarchman** [comment]
Perfect.

The only other thing would be to add a warning that you must click past,
e.g., "You are about to add XXX number administrations to your study.  Are
you sure?"

But it's not necessary, if you think this is sufficient.
