### ISSUE TITLE
updates to English WS clinical report

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#458]
@HenryMehta There are a few updates to the English WS clinical report (the Word endings section)
[EnglishWSClinicalReport_updated.docx](https://github.com/langcog/web-cdi/files/11682627/EnglishWSClinicalReport_updated.docx)
.  Attached is the new version.

For the 4 new responses (spossess, splural, ed, ing), the responses are: blank and "not yet" = No, "sometimes" and "often" = Yes.

**Comment by HenryMehta** [comment]
@vmarchman How do I know which response is which?  What are the items/questions which give me the results

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> Sorry if that was not clear.  These are not
summary statistics, but rather the actual items.

[image: image.png]

**Comment by HenryMehta** [comment]
@vmarchman If it is individual items I can probably do it, but I need to know the itemID and that image isn't helping me.  If it is a sum, then it needs to be included in the scoring

**Comment by HenryMehta** [comment]
@vmarchman found them !

**Comment by vmarchman** [comment]
ok cool!!  Thanks @Henry ***@***.***>

**Comment by HenryMehta** [comment]
@vmarchman deploying to dev now

**Comment by HenryMehta** [comment]
@vmarchman please confirm if this is ok

**Comment by vmarchman** [comment]
Yes, @Henry ***@***.***> clinical report looks good.  Thanks.
