### ISSUE TITLE
studies not showing up in dialog box

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#459]
A user reports that they have an existing study that suddenly has disappeared from their dropdown menu of studies.  They have tried to login and log back in but the study is still missing.  When I login as admin, I can see the study just fine with multiple completed cdis.  Thoughts @HenryMehta ?

**Comment by HenryMehta** [comment]
@vmarchman Can you give me the specific study?  It sounds like they've probably deleted it

**Comment by HenryMehta** [comment]
@vmarchman Any luck with the researcher and study name so I can investigate a little more

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***>  - Yes, just confirmed that she still can't
see this study in her dropdown, but I can see it in admin:

[image: image.png]

**Comment by HenryMehta** [comment]
@vmarchman It was no longer active so she had deleted it.  I've made it active again.  See if she can see it now

**Comment by vmarchman** [comment]
Yes!  She sees the study now.

@Henry ***@***.***>  There was also a participant with a completed
administration in that study.  ID #2216 - it appears to have been deleted.
Do you see that?

**Comment by HenryMehta** [comment]
@vmarchman Sorry, I cannot see it.  I'm guessing she/he deleted that as well as the study.  Unfortunately deleted administrations are actually deleted from the database rather than just hidden from the researcher

**Comment by vmarchman** [comment]
@Henry ***@***.***> bummer.  Is there a way to have administrations
also just be archived, rather than actually deleted?

**Comment by HenryMehta** [comment]
Yes, but it would take some work.  We would need to raise it as another issue rather than doing as part of this work

**Comment by vmarchman** [comment]
gotcha.
