### ISSUE TITLE
custom style researcher login page

### ISSUE THREAD

**Issue by mikabr** [langcog/web-cdi#46]

**Comment by bengittelson** [comment]
Can someone provide more detail on this?

**Comment by mcfrank** [comment]
I think so it looks official. this is a beta not an alpha feature. For
alpha we want something that works for parents that we can use to collect
some basic data.

Mike

**Comment by mcfrank** [comment]
login page in particular is ugly.

**Comment by daniellekellier** [comment]
Login page is prettier. Perhaps it can be replaced with a modal window in the future but for now bootstrap and crispy forms are making it a lot prettier.
