### ISSUE TITLE
not being able to create study with more than 28 days for link expiration

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#460]
when we toggle longer than the default link expiration we get an error and the dialog of the ages of the kids goes wonky.  We also get an old error message that says "must be < 28 days"

![image](https://github.com/langcog/web-cdi/assets/7682636/632e3f9b-d4bf-40d1-a60a-bc7b62d04a8e)

**Comment by HenryMehta** [comment]
@vmarchman deploying now to dev for test

**Comment by HenryMehta** [comment]
@vmarchman 
I have amended the study create and update forms so that hitting return does not submit it.  I think that is everything working on these forms now.  If I've missed something please let me know

**Comment by HenryMehta** [comment]
@vmarchman I've also set it up so when you create a study, it is automatically loaded for the researcher and you don't have to select it from the list

**Comment by vmarchman** [comment]
Yes - that helps a lot.  Thanks @Henry ***@***.***>

**Comment by HenryMehta** [comment]
@vmarchman , Are you happy for me to deploy this to production?

**Comment by vmarchman** [comment]
Yes - thank you @Henry ***@***.***>
