### ISSUE TITLE
demographic opt-out reverts after a few participants

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#470]
@HenryMehta A user came to me to say that when they set up a study with demographic/sharing opt out, after a few test participants, the demographics shows up again.  One time it was after they deleted one test participant, but another time, they did not delete any participants.  The user is feldmanlab and the study is AFECT WG - Spanish.  I've gone in an manually updated the settings to opt out and it seems to be working now.  The user will (1) test the study that I updated to see if demographics comes back (reverts) and (2) create a new study, opt out, and then test to see if things revert.

**Comment by HenryMehta** [comment]
@vmarchman How urgent is this?  Do I need to fix as part of French CAT or can it wait till after the API work?  I would rather delay it or include with API work

**Comment by vmarchman** [comment]
@HenryMehta I'll have her test to see if we can make it break again, but she's wanting to start participant testing next week.

**Comment by HenryMehta** [comment]
@vmarchman I suspect the way it is broken is through "Update Study"

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> the user has tested extensively today and
can't seem to replicate the issue. So I guess we just assume it was user
error. Sorry!
