### ISSUE TITLE
updating study reverts to old settings for demographics and sharing

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#472]
@HenryMehta We thought this was user error, but indeed, when someone updates a study that has previously opted out of sharing/demographics, the settings revert to the default.  Not terribly urgent, but could be annoying for some users.

**Comment by vmarchman** [comment]
Maybe the solution is to simply add those choices to the update study dialog

**Comment by HenryMehta** [comment]
@vmarchman deploying update to dev now

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***>   I'm confused by the options now.  In the
default version of the New Study dialog, in the Demographic options, I can
click on a new demographic opt out option, even if I haven't selected opted
out of sharing.  but, then when I click on the opt out of sharing, I get
the standard opt out option.

[image: image.png]

**Comment by HenryMehta** [comment]
@vmarchman because you didn't respond on GitHub I cannot see the image but I think I know your issue.

We have a new checkbox within Demogrpahics which will be used by the UCSD team, and anyone else who wants to, by which we collect no demographic data at all.  This is not about sharing information.  This is used when the demographic data is being collected within RedCAP as an example.

If you do select this option, you will see in the links you have to share that age, offset and sex need to be included within the link to WebCDI.

**Comment by vmarchman** [comment]
@Henry ***@***.***> Sorry - but, we don't want folks to opt out of
demographics unless they have opted out of sharing.  If folks are
collecting demographic information in RedCap we don't have access to that
information within WebCDI, so it is not useful to us.

Can't we put that information in the dialog about setting up RedCap?

I don't want it to be a general option. Right now, it will just cause
confusion.

**Comment by HenryMehta** [comment]
@vmarchman ok, I'll amend tomorrow morning so you can only opt out of demographics if opted out of sharing

**Comment by HenryMehta** [comment]
@vmarchman Amendment deployed

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> Thank you.

However, I'm still not sure about the 2 options currently in Demographic
options.  I know the one is for RedCap users, etc., but I fear folks will
choose it and get confused.

Options?

**Comment by vmarchman** [comment]
Yes @Henry ***@***.***>  Thank you!

(1) One of the options appears grey out, and one appears only if you choose
opt out.  Can both only appear when opt out?

(2) Can you change the order of the two options?  So, Minimum data
collected is first (and the most typical use-case) and then the URL one.
 Can the Minimum Data collected be checked by default?

Change wording to be "Minimum demographic data (age, sex, age offset)
provided directly by participant".

(3) Further on down - Can the "do you want confirmation questions?"
question only show up if users select the non-default demographics?

**Comment by HenryMehta** [comment]
@vmarchman You don't want minimum data to be checked by default.  It will mean all the questions about income, birth order, weight etc will not be asked.

I have amended the order, wording etc and the url link only shows once the minimum data item is checked.  You'll see what I mean

**Comment by HenryMehta** [comment]
Video here: https://youtu.be/oGFFlY7PIIY

**Comment by vmarchman** [comment]
Ahhh.  Yes @Henry ***@***.***>   Actually, I misspoke I think.  I
must have been thinking to have a new default checked which is collect all
demographic data.  But, I think your solution works - i.e., to not have the
options about minimum data be available unless you select opt out.
