### ISSUE TITLE
add more description to Add Participants dialog box

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#473]
@HenryMehta There is some confusion that the user needs to put information in ALL of the dialog boxes.  Please add the following description to the top section of the box.

Use ONE of these options to add participants to your interface.  Use the "New Subject Ids" option to create links using your own ID numbers (numeric only).  Typically, this is done in small batches when you are ready to send out the links.  Use the "Autogenerate" or "Upload CSV" dialog if you want to create many links at the same time. In all cases, subject IDs should not include any identifiable information and are enforced to be numeric.  Note that all links will expire in the time (default = 14 days) from their creation.

**Comment by HenryMehta** [comment]
@vmarchman deploying to dev now

**Comment by vmarchman** [comment]
Thanks. Looks great @Henry ***@***.***> !
