### ISSUE TITLE
clinical reports use chronological age, not age to compare

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#475]
@HenryMehta In the csv outputs, when a child is born prematurely, you can ask for outputs with both chronological and adjusted benchmark ages.  But, in the clinical report, there is only 1 option.  That option gives you "Age to compare" that is the adjusted age, but then the percentiles are the non-adjusted ones.

Solution:  Add new clinical report option with adjusted benchmarks, analogous to the csv output options.  If you choose "Clinical Report" you get the chronological benchmarks - and the age to compare should be the same as chronological age and the percentiles are the unadjusted ones. 

If you choose "Clinical Report with adjusted benchmarks" you get adjusted "Age to Compare" and the adjusted percentiles.

**Comment by HenryMehta** [comment]
@vmarchman deploying to dev now

**Comment by vmarchman** [comment]
Thanks @HenryMehta!! Tested in dev.  Option for two clinical reports is in dropdown and works fine.  But, both clinical reports are the same.  That is, both use the chronological age percentiles.  The "Clinical report" is correct since we want that one with the chronological age percentiles (and the Chronological age and Age to compare should be the same).  

The "Clinical report with Adjusted Percentiles" is NOT correct.  We want that one to spit out the adjusted benchmark percentiles.  The Age to compare should be different than the Chronological age.

*Everything is correct in the csv outputs.

*Typo in label in dropdown - "Adjusted benchmarks"

**Comment by HenryMehta** [comment]
@vmarchman could you tell me which report you're testing on.  I don't have data with different results

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> I was testing with Study test WG, subject
1111, administration 25.

I'm using administration #26 to test the 0 responses (issue 481)

**Comment by HenryMehta** [comment]
@vmarchman try now

**Comment by vmarchman** [comment]
Yes - working now!  Thanks @HenryMehta
