### ISSUE TITLE
autogenerate new participants fails

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#48]
I get a 400 server error

**Comment by AshwinParanjape** [comment]
It is working for me :-/

**Comment by mcfrank** [comment]
OK got it - it's only when you hit "enter" to submit that form, not when
you click submit. And it's a 500 error.

thanks

Mike

**Comment by mikabr** [comment]
Error generated by clicking enter instead of submit:
```
ValueError at /interface/study/cats/
The view researcher_UI.views.console didn't return an HttpResponse object. It returned None instead.
```
