### ISSUE TITLE
WG clinical report

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#481]
@HenryMehta the English WG clinical report spits out "Summary data matching query does not exist" when scores for Words Understood and Words Produced are 0.   Should spit out 0.

Not sure if this applies to all variables.  But 0 is a legitimate response.

**Comment by HenryMehta** [comment]
@vmarchman deploying to dev now

**Comment by vmarchman** [comment]
@HenryMehta Tested on English WG and WS.  Looks good!
