### ISSUE TITLE
completion date is missing in csv output?

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#483]
@HenryMehta This is a column that used to be in the csv outputs (apparently).  Is there a reason why it is no longer being populated? 
Is it the same as "last modified"?

**Comment by HenryMehta** [comment]
@vmarchman I have just tested in dev and it seems to me there was a period when completed_date was not being completed, but it is now.

I have written, and will run in dev when I'm happy with my testing (which I'm doing now), a program to populate those which are completed but without a completion date.  I'll let you know when run.

Are the completion dates you've referenced above recent or from pre September?  If recent, there is an issue I have not found.  In this case, I will need the Study the researcher is user so I can track the issue.

**Comment by HenryMehta** [comment]
@vmarchman I cannot run the update directly.  I've set it to run at midnight.  You should be able to review from Sunday morning
