### ISSUE TITLE
spanish language compat

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#5]
need to figure out how to link demographics model to a particular form's language, should be a method of the demographics model.

**Comment by daniellekellier** [comment]
Refs: 
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/
http://www.marinamele.com/taskbuster-django-tutorial/internationalization-localization-languages-time-zones#inter-urls

**Comment by daniellekellier** [comment]
http://django-modeltranslation.readthedocs.io/en/latest/index.html
https://simpleisbetterthancomplex.com/tips/2016/10/17/django-tip-18-translations.html
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#lazy-translation
https://stackoverflow.com/questions/2336785/set-language-within-a-django-view
https://medium.com/@nolanphillips/a-short-intro-to-translating-your-site-with-django-1-8-343ea839c89b

**Comment by daniellekellier** [comment]
http://django-modeltranslation.readthedocs.io/en/latest/index.html
