### ISSUE TITLE
gift card functionality

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#502]
Web-CDI allows users who complete Web-CDI to receive gift cards from Amazon. 

(1) Check functionality to make sure that it works properly.

(2) Expand functionality to include other vendors, in particular, Tango. 

Since we need to validate the gift cards somehow, we need to have specific formats built in.  So, it can't be general to whatever system, correct?  Users would then be required to choose a particular system, i.e., Amazon vs. Tango, similar to how they do for the external links (i.e. RedCap vs. Lookit).

@HenryMehta Can you give an estimate for completing (1) and (2)?

Thanks!

**Comment by HenryMehta** [comment]
Deployed to production
