### ISSUE TITLE
extend norms for English CAT to 36 months

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#509]
@HenryMehta We have figured out a way to have the norms for the English CAT extend to 36 months.  I think that all is involved is:

(1) extend maximum benchmark age from 30 to 36 months.  So, all folks up to 36 months will be compared to their actual (or corrected) age, and all folks older than 36 months will be compared to 36 months.

(2) @kachergis put the tables for the Theta look ups in slack but the link is here: [https://rpubs.com/kachergis/CDI-CAT-EN-norms]

(3) here are the tables for the vocabulary conversion, i.e., to look up what vocabulary score is equivalent to a particular theta:

[WSprod_both_36months.csv](https://github.com/langcog/web-cdi/files/14620950/WSprod_both_36months.csv)
[WSprod_boys_36months.csv](https://github.com/langcog/web-cdi/files/14620951/WSprod_boys_36months.csv)
[WSprod_girls_36months.csv](https://github.com/langcog/web-cdi/files/14620952/WSprod_girls_36months.csv)

Nothing about the WS or WG norms will change or the Spanish CAT will change.

Let me know if you have any questions!

**Comment by HenryMehta** [comment]
@vmarchman The girsl file only shows to 30 months

**Comment by vmarchman** [comment]
@HenryMehta Ok - sorry - Here's the corrected girls file.
[WSprod_girls_36months.csv](https://github.com/langcog/web-cdi/files/14637846/WSprod_girls_36months.csv)

At this point, we want the WS norms to remain the same.  The extension out to 36 months will only happen with the CAT.  I don't want to extend the WS because, as you say, it's only the production and the other variables will be out to 30 months, so the "benchmark" age will not apply consistently across the variables.

Is it possible to use one set of files for the CAT and another for the WS?

**Comment by HenryMehta** [comment]
@vmarchman I have amended and loaded.  I believe you should now get the right benchmarks upto 36 months for CAT, and only up to 30 months for WS (or WG, I cannot remember which).

I will be doing some more testing later, but it is good for you to test now as well

**Comment by kachergis** [comment]
Great, thanks Henry!
Do you have experience writing automated tests (e.g. using `unittest`*)?
WebCDI seems like a great candidate for tests... Probably well worth
setting up, and I'm sure I and others could help write tests if needed.

*https://docs.djangoproject.com/en/5.0/topics/testing/

**Comment by HenryMehta** [comment]
@vmarchman I can write unit tests for the site, but this shouldn't remove the need to user test and ensure the process is working correctly.  A unit test will do something like, create a study for American WS (and if we want to test every instrument we write a test for every instrument).  But it won't test the actual user experience.  But I can certainly write them.

**Comment by kachergis** [comment]
agreed, still also necessary to test manually!

**Comment by vmarchman** [comment]
@Henry ***@***.***> Sorry for the late reply.  re building the
tests:  Let me discuss at the CDI meeting tomorrow.

I'll try to manually test CAT today and get back to you asap.

Virginia

**Comment by vmarchman** [comment]
Hi @Henry ***@***.***> I've tested CAT and things look good now.

re tests. If you think that they are useful, @George Kachergis
***@***.***> makes a good case for them.  If you want to
work on some as we go along, that's fine, but only if we don't have other
priorities.  I understand that there will still be the need for "real" user
testing (i.e., me) :-)

Best,

Virginia

**Comment by HenryMehta** [comment]
Hi @vmarchman, yes, the can be useful.  I'll work on a few

**Comment by HenryMehta** [comment]
@vmarchman CAT changes a live.  I'll close this and open a test script ticket

**Comment by vmarchman** [comment]
Thank you @Henry ***@***.***> !
