### ISSUE TITLE
[Japanese CDI-CAT] remove unneeded line breaks on multiple choice questions

### ISSUE THREAD

**Issue by kachergis** [langcog/web-cdi#523]
From Sho: "A lot of the multiple choice Qs in the beginning have weird type setting (at least on my computer screen) - e.g. whether it is a girl or boy, or Q's that require a "yes" or "no". These are very short answers but still the JP kana go over two lines."
Further clarification:
"there are some line breaks that seem avoidable, such as: 
男
の子

Instead of:
男の子

or:
いい
え

Instead of: 
いいえ

Would it be possible to have them in one line?"

Eliminate extra line breaks, or if needed make the column wider?

**Comment by HenryMehta** [comment]
This is being done automatically via the html.  It judges there isn't space.  I can look at modifying the padding/margins or running the options over multiple lines but it will mean testing every language and every form.  Please confirm
