### ISSUE TITLE
[Japanese + French CDI-CAT] Child weight: should allow choice of metric (kg) or imperial (lbs/oz) - researcher failure should not create impossible to complete administrations

### ISSUE THREAD

**Issue by kachergis** [langcog/web-cdi#525]
Henry says:
"With the kgs instead of lbs, it does mean they must select kgs as the measurement when setting up the study.  If they don’t, participants will not get past the demographics page." 
-> Maybe I misunderstand, but I think we should not allow researchers to create administrations that participants can't complete: how can we solve this? (form validation, setting defaults...?)

From Sho:
"Child’s weight: g/oz I agree with Hiromichi and I remember a long discussion we had for French. In French we added oz in brackets if I recall correctly? I think Cécile and I were not very happy even with the final solution since we would have preferred kg and it was kept in g, and it is very unnatural in French, but that you had reasons for it... but we do not need to reassess all of this ;), just to say whatever was done in French can also work in Japanese although I want to remind you that it still looks weird for these languages!"

**Comment by HenryMehta** [comment]
I think I've now implemented this, but it impacts all languages and demographic forms so I'm running tests
