### ISSUE TITLE
[Japanese CDI-CAT -- all CDIs?] mandatory vs. optional questions - caregiver education, 2nd language, health Qs

### ISSUE THREAD

**Issue by kachergis** [langcog/web-cdi#526]
From Sho:
"- The question on caregiver education question is now a mandatory one, while the wording (the term in brackets) suggests it is optional. In general I agree with Hiromichi that if possible this should be optional, but for education we can keep it mandatory if necessary. However, family income absolutely needs to be optional.

- If I indicate that the child hears a 2nd language, then the follow-up Qs are not marked as mandatory, but if I do not fill them in I get an error message. Mark as mandatory or make optional. (@HenryMehta is this a bug?)

- The questions on health: They are mandatory but there is an option "Do not want to provide info". I somewhat understand this is done to make sure a Q is not just skipped versus consciously not answered, but it seems not very logical given there are other non-mandatory questions that do not have such an option..."

These seem indicative of a broader need to review mandatory question options, and consider whether they should just be optional questions?

**Comment by vmarchman** [comment]
My answers below to the best of my knowledge.  -vm

On Thu, Jun 27, 2024 at 9:48 AM George Kachergis ***@***.***>
wrote:

> From Sho:
> "- The question on caregiver education question is now a mandatory one,
> while the wording (the term in brackets) suggests it is optional. In
> general I agree with Hiromichi that if possible this should be optional,
> but for education we can keep it mandatory if necessary. However, family
> income absolutely needs to be optional.
>
>    -
>
>    If I indicate that the child hears a 2nd language, then the follow-up
>    Qs are not marked as mandatory, but if I do not fill them in I get an error
>    message. Mark as mandatory or make optional. ***@***.***
>    <https://github.com/HenryMehta> is this a bug?)
>
> The questions to provide information on 2nd language should be marked as
mandatory if one indicates Yes.

>
>    -
>    -
>
>    The questions on health: They are mandatory but there is an option "Do
>    not want to provide info". I somewhat understand this is done to make sure
>    a Q is not just skipped versus consciously not answered, but it seems not
>    very logical given there are other non-mandatory questions that do not have
>    such an option..."
>
> These seem indicative of a broader need to review mandatory question
> options, and consider whether they should just be optional questions?
>
We are required to allow participants to "opt out" of responding to
mandatory information.  so, yes, we require some sort of response, of which
"Prefer not to respond" is a valid option to a mandatory question.  It was
my understanding that all mandatory questions had that option.  Can you
clarify which questions are mandatory but do not have a prefer not to
respond option?  Thanks.

**Comment by mcfrank** [comment]
Yes, I agree that this is important - we need to review what's mandatory
and what's optional here for the CATs and more generally.

**Comment by HenryMehta** [comment]
If we ignore the default demographic form (which Japanese is no longer using), then, with the exception of dob (and 1 other I cannot remember off the top of my head), we can make whatever questions you want mandatory/not-mandatory.  Different languages have asked for and been given different things, including some of the responses available.
