### ISSUE TITLE
[Japanese CDI-CAT] update "Primary Caregiver" text

### ISSUE THREAD

**Issue by kachergis** [langcog/web-cdi#527]
From Sho:
"The "Primary Caregiver" Q does not contain the correct translation (added it as a comment in the spreadsheet)"
https://docs.google.com/spreadsheets/d/1aG9eTxuWRNmJyCeZRGMuh9dsDsBJYEa0fu80bHGMv7g/edit?usp=sharing

**Comment by HenryMehta** [comment]
I have changed from お子さまを主に養育している方 (＝主たる養育者) はどなたですか to お子さまの主たる養育者はどなたですか？.

I hope this is correct
