### ISSUE TITLE
Update tables for English CDI-III complexity

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#529]
Unfortunately, there was an error in the look-up tables for American/Canadian English CDI-III complexity section.  @HenryMehta Please update with these new tables.

[IIIcomplex_both_updated.csv](https://github.com/user-attachments/files/16119326/IIIcomplex_both_updated.csv)
[IIIcomplex_boys_updated.csv](https://github.com/user-attachments/files/16119327/IIIcomplex_boys_updated.csv)
[IIIcomplex_girls_updated.csv](https://github.com/user-attachments/files/16119328/IIIcomplex_girls_updated.csv)

**Comment by HenryMehta** [comment]
@vmarchman 
Can you confirm ages 1,2,3,4 refer to 30-31, 32-33, 34-35 and 36-37 months please

**Comment by vmarchman** [comment]
Yes @Henry ***@***.***> that is correct

**Comment by HenryMehta** [comment]
@vmarchman I've updated the tables in test.  Do you want to test?
