### ISSUE TITLE
researcher guide needs filling in

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#53]
https://docs.google.com/document/d/1naFm2U-77YcOwFD7jcQIes2HhNz98qQM2wm1J1cmwck/edit

**Comment by HenryMehta** [comment]
@mcfrank, @vmarchman 
Due to changes and additional features being added to the system I've been doing some changes to the researcher documentation which I've loaded within the Wiki here: https://github.com/langcog/web-cdi/wiki/Researcher-Manual

**Comment by vmarchman** [comment]
Thanks @HenryMehta!  btw, is there documentation somewhere that outlines the database structure? not an action item, but just wondering.

**Comment by HenryMehta** [comment]
@vmarchman No, there isn't
