### ISSUE TITLE
clinical reports for kids with adjusted benchmarks (born early)

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#536]
@HenryMehta For children who are born premature, when you click on Clinical report with adjusted benchmarks, the report is fine.  But, when you click on the report for the regular Clinical report, it populates all zeros.  The raw scores should populated just as in the adjusted benchmark report, but the percentiles should be based on unadjusted (chronological) age.

Example: 
For WG, a child is 25 months (chron), born 1 month premature so adjusted age is 24 months.  His benchmarking age is 18.  The report works fine.

For WG, that same child's report populates 0 when you ask for the standard Clinical report.  The benchmarking ages should be the same.  
Alternatively, we can have an error that says the report will not be printed because the child is born premature.....?

**Comment by HenryMehta** [comment]
@vmarchman Can you include an image of the report please

**Comment by HenryMehta** [comment]
I have just completed a test study and all seems ok to me so I don't understand what you've spotted.   Clinical and Adjusted reports attached

[clinical.pdf](https://github.com/user-attachments/files/16707220/clinical.pdf)
[adjusted.pdf](https://github.com/user-attachments/files/16707222/adjusted.pdf)

**Comment by vmarchman** [comment]
@Henry ***@***.***> I was working with a student in her study.
You're right - it seems to work fine in my study, so let me reach out to
her and see if she is still having issues.  thanks.
