### ISSUE TITLE
non-integer responses for birth order

### ISSUE THREAD

**Issue by bengittelson** [langcog/web-cdi#54]
When I try to input a non-integer answer for the birth order question (e.g. “second,” “third,” “two,” etc.),  it deletes it without giving me any kind of error message. We should change it to a dropdown or specify that we want integer answers.

**Comment by mcfrank** [comment]
Yes, agreed, that sounds right.

Mike

**Comment by bengittelson** [comment]
I think this problem may have been caused by the computer/browser I was using since it forces me to use up and down arrows in Chrome and Safari on my laptop. If anyone else can replicate this issue, I'll try to fix it but will otherwise close it.
