### ISSUE TITLE
negative values for language exposure

### ISSUE THREAD

**Issue by bengittelson** [langcog/web-cdi#58]
"How many days per week is the child exposed to these languages" and "How many hours per day is the child exposed to these languages" allow for negative answers

**Comment by bengittelson** [comment]
This has been fixed, although I set the minimum hours/day to 1 since it seems like 0 would indicate that the child doesn't actually get any exposure to that language. Does this mean hours per day on average? If so, it might be helpful to clarify that on the form. Or should we allow parents to input values in increments that are smaller than one hour?

**Comment by mcfrank** [comment]
Seems like a good idea. And yes, this is average.

Mike

**Comment by vmarchman** [comment]
Should we rephrase to be:  "In a typical week, how many days is the child
exposed to these languages?" and "In a typical week, how many hours per day
is the child exposed to these languages?"

Or more simply, if the questions are right next to one another:

So: "In a typical week, how many days is your child exposed to these
languages?" and "How many hours per day?"
