### ISSUE TITLE
fix typos/grammatical errors

### ISSUE THREAD

**Issue by bengittelson** [langcog/web-cdi#59]
see bottom section of this Google Doc: https://docs.google.com/document/d/1ptdL6vVBg4CSrABvmLQaRjSAoJioHaudGBnr7tHKidM/edit

**Comment by bengittelson** [comment]
I'm marking this as closed since I've done the first round of typo fixing, but this will likely require continued attention as the site changes.

**Comment by mcfrank** [comment]
great!

Mike
